### ISSUE TITLE
Project > Goals >  Getting "Goal selection is required" error momentarily when user create a "Film" goal and goal is already selected

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1007]
**Roles:** All

**Describe the bug**
Project > Goals >  Getting `Goal selection is required` error momentarily when user create a `Film` goal and goal is already selected

**Steps to Reproduce**
1.  Login as a root user
2.  Create a project and open a project detail page
3.  Add `LanguageEngagement` and click on the `View Details`
4.  Click on the `Add Goal` button and select `Film` from the goal dropdown
5.  Add other details and click on the `Save Goal` button

**Expected Result**
Goal should be created without error

**Actual Result**
 Getting `Goal selection is required` error momentarily when user create a `Film` goal and goal is already selected

See video - 

https://user-images.githubusercontent.com/5212585/140723813-99607020-90d7-4e6a-8776-df63f6c12be9.mp4

![Screenshot (49)_LI](https://user-images.githubusercontent.com/5212585/140724230-51f87a6d-0fcb-4d13-8dc6-d2a04609389c.jpg)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# d8b9268

**Comment by daniel-leod** [comment]
@iPiyushPatel Could you please review this issue and tell if you can still reproduce it? Thanks!

**Comment by iPiyushPatel** [comment]
@daniel-leod 
Verified on latest develop 08c3368 and it's working fine. Now you can close the issue
Thanks 

See video : 

https://user-images.githubusercontent.com/5212585/144979795-945c44d2-c522-4fe3-bb47-09c86a3f8553.mp4

**Comment by iPiyushPatel** [comment]
Hi @daniel-leod 
Recently I've faced this issue again on the latest develop 24f02f4
Please find this attached video 
Thanks

See video : 

https://user-images.githubusercontent.com/5212585/153859553-324d7a2d-459b-439f-9b7b-e96a2ced00c7.mp4


![image](https://user-images.githubusercontent.com/5212585/153859221-d8d1652e-883d-44b6-9084-a17f11e6bb72.png)
