### ISSUE TITLE
Create Location > Funding Account > Getting "Variable "$input" got invalid value null at "input.fundingAccount.accountNumber"; Expected non-nullable type "Int!" not to be null." error when user leave blank "Account Number" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1014]
**Roles:** All

**Describe the bug**
Create Location > Funding Account > Getting `Variable "$input" got invalid value null at "input.fundingAccount.accountNumber"; Expected non-nullable type "Int!" not to be null.` error when user leave blank `Account Number` field

**Steps to Reproduce**
1. Login as an admin user
2. Create a location and create a funding account
3. Leave field `Account Number` blank
4. Click on the `Submit` button

**Expected Result**
Proper validation message should be displayed

**Actual Result**
Getting `Variable "$input" got invalid value null at "input.fundingAccount.accountNumber"; Expected non-nullable type "Int!" not to be null.` error when user leave blank `Account Number` field

See video - 

https://user-images.githubusercontent.com/5212585/141268007-d4022724-c3a5-46d2-bcb9-10e021e28209.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# edfea9d

**Comment by daniel-leod** [comment]
This issue can be closed via the PR linked. This [line](https://github.com/SeedCompany/cord-field/pull/962/commits/04627fcfaa5e6d3db9653901751e355c5f784eb8#diff-026bdb8fcd44bf1e26bfb4fd79e23e71ca2af965ca20f3bee40df3739d1e05f5R49) fixes it

**Comment by iPiyushPatel** [comment]
Hi @daniel-leod @CarsonF
I've verified on the latest develop a54e2cd and it's working fine for the Create Location>Account Funding and getting the required validation message for the blank Account Number field . Attaching a video for a reference. Thanks!

See video:
