### ISSUE TITLE
Develop "Pin" Animation

### ISSUE THREAD

**Issue by AmyRickwartz** [SeedCompany/cord-field#1015]

**Comment by AmyRickwartz** [comment]
Designs can be found here:
[FOR DEVELOPMENT - Cord Field > Projects - Favor Subscribe](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/FOR-DEVELOPMENT---Cord-Field?node-id=4623%3A786)

When I designed this I didn't use the "ripple" effect that is live on CF currently. I need to update this file sightly to reflect that. However, if development picks this up in the mean time—the animation action is moving the "pin" -45° to show if an item has been pinned.

**Comment by ParkeBrown** [comment]
@sethmcknight FYI

**Comment by tmpacifitech** [comment]
> Designs can be found here: [FOR DEVELOPMENT - Cord Field > Projects - Favor Subscribe](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/FOR-DEVELOPMENT---Cord-Field?node-id=4623%3A786)
> 
> When I designed this I didn't use the "ripple" effect that is live on CF currently. I need to update this file sightly to reflect that. However, if development picks this up in the mean time—the animation action is moving the "pin" -45° to show if an item has been pinned.

@AmyRickwartz I need permission to access this figma file.

**Comment by AmyRickwartz** [comment]
Hi Thain @tmpacifitech ,
The Figma file says you have viewing access. Perhaps you are not using the same email that you had used previously in Figma? I can’t see what email it says you are registered with…I had the issue with Carson once.
