### ISSUE TITLE
Project > Goals > "Steps" are not changed after clicking on "Visual-other" methodology

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1019]
**Roles:** All

**Describe the bug**
Project > Goals > `Steps` are not changed after clicking on `Visual-other` methodology

**Steps to Reproduce**
1.  Login as a root user
2.  Create a project and open a project detail page
3.  Add `LanguageEngagement` and click on the `View Details`
4.  Click on the `Add Goal` button and click on the `methodology` dropdown
5.  Select `Visual - film` methodology
6.  Select `Visual - Sign Language` methodology
7.  Select `Visual - Other` methodology
8.  Select `Visual - film` methodology

**Expected Result**
`Steps` should be changed for `Visual- Sign Language` &  `Visual- film` methodology type after clicking on  `Visual-other` methodology

**Actual Result**
`Steps` are not changed after clicking on `Visual-other` methodology

See video - 

https://user-images.githubusercontent.com/5212585/142194414-edfce8b1-1679-4ffd-951c-586c7756b910.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 7b2519a

**Comment by daniel-leod** [comment]
It also happens when changing goal type from `Ethno Art` to `Other` to `Ethno Art` again.
