### ISSUE TITLE
Project > Goals > "Steps" value is fixed for "Ethno Art" and "Other" goal type

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1021]
**Roles:** All

**Describe the bug**
Project > Goals > `Steps` value is fixed for `Ethno Art` and `Other` goal type

**Steps to Reproduce**
1.  Login as a root user
2.  Create a project and open a project detail page
3.  Add `LanguageEngagement` and click on the `View Details`
4.  Click on the `Add Goal` button and select `Ethno Art` goal type
5.  Select methodology 
6. Click on the `Add Goal` button and select `Other` goal type
7. Select methodology 

**Expected Result**
`Steps` value should be changed according to goal type and methodology

**Actual Result**
`Steps` value is fixed for `Ethno Art` and `Other` goal type

See video - 

https://user-images.githubusercontent.com/5212585/142390726-e43b66f7-0d4b-42b5-bdad-f1338f3d8c61.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# a43f7c0

**Comment by daniel-leod** [comment]
I think this is working as expected. [Here ](https://github.com/SeedCompany/cord-api-v3/issues/2081#issuecomment-947061113)is a reference about the available steps for `Ethno Art` and `Other` goals.
