### ISSUE TITLE
Project > Goals >"Completed" text is shown instead of "Complete"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1027]
**Roles:** All

**Describe the bug**
Project > Goals > `Completed` text is shown instead of `Complete`

**Steps to Reproduce**
1.  Login as a root user
2.  Create a project and open a project detail page
3.  Add `LanguageEngagement` and click on the `View Details`
4.  Click on the `Add Goal` button and select `Scripture` goal type
5.  Select methodology `Visual` methodology

**Expected Result**
Step value should be displayed `Completed`

**Actual Result**
`Completed` text is shown instead of `Complete`
 
 **Note:**  Please find this attached [document](https://github.com/SeedCompany/cord-api-v3/issues/2081) for your reference,

See screenshots - 

![image](https://user-images.githubusercontent.com/5212585/142815820-d25a92b1-fec7-41f9-8acb-017d2ea1c1aa.png)

![image](https://user-images.githubusercontent.com/5212585/142810400-ac5ead60-a13a-4a84-86d0-0420c74924ba.png)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# a43f7c0

**Comment by CarsonF** [comment]
Yeah I wanted to be consistent with the others. I didn't want `Completed` and `Complete`. I assumed this was ok. @sethmcknight?

**Comment by sethmcknight** [comment]
This is fine
