### ISSUE TITLE
Project > Team Members > User role is not updated when the created Person's "Role" is changed

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1029]
***Roles:*** All

**Describe the bug**
Project > Team Members > User role is not updated when the created Person's `Role` is changed

**Steps to Reproduce**
1.  Login as a root user
2.  Create a new person
3.  Create a new project and add the created person to the team member
4.  Click the people module and edit the role for the created person and click on the `submit` button 
5.  Click on the created project and click on the team member button

**Expected Result**
Updated person's details should be displayed

**Actual Result**
User role is not updated when the created Person's `Role` is changed

See video - 

https://user-images.githubusercontent.com/5212585/143009534-25e7dc60-b76d-4caa-8175-1e3765205e11.mp4

***FYI:*** @ParkeBrown @michaelmarshall 

cord-field# 694a111

**Comment by CarsonF** [comment]
These are two different lists @iPiyushPatel. For example a user could be a Consultant, kind of like a job position, and that role on their user grants them certain permissions. But that doesn't mean the user is a fulfilling a Consultant role in a certain project, maybe they are doing something else or are just a member without any roles.
