### ISSUE TITLE
Cannot add Partners producing product mediums as consultant manager

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1039]
**Roles:** Consultant Manager

**Describe the bug**
Project > Goal > `Partners Producing these Distribution Methods` is not added when the user create a product

**Steps to Reproduce**
1. Login as a root user
2. Create a project and add `Consultant Manager ` as a team member
3. Add partnership
4. Login with `Consultant Manager` user and open root user-created project
5. Add language engagement and click on the `View Details` button
6. Click on the `Add Goal` button and create a goal

**Expected Result** 
`Partners Producing these Distribution Methods` should be added

**Actual Result**
 `Partners Producing these Distribution Methods` is not added when the user create a product

See video - 

https://user-images.githubusercontent.com/5212585/143415475-550f3bf0-2f72-4b82-8eb0-695f190b1953.mp4

FYI @ParkeBrown @michaelmarshall 

cord-field# 5c78c6f

**Comment by CarsonF** [comment]
@sethmcknight Should Consultant Manager have permission to change these?

**Comment by daniel-leod** [comment]
Seems like the Consultant Manager role does not have permissions to edit Distribution Methods according to [Sensitive Field Permissions doc](https://docs.google.com/spreadsheets/d/1GBAyYtzztRGgdIJY44XI27obITYCEDkxY_mLk9IS4jE/edit#gid=1648651465)

![image](https://user-images.githubusercontent.com/36520121/172729646-5f5d4dbb-ac28-47d6-b78c-ebdb31addd0a.png)
