### ISSUE TITLE
Project > Files > Uploaded file is not displayed when the user uploads the file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1040]
**Roles:** All

Describe the bug
Project > Files > Uploaded file is not displayed when the user uploads the file

**Steps to Reproduce**
1.  Login as a root user
2.  Create a new project 
4.  Click the `upload files` icon and upload the file
5.  Click on the `View Files` 

**Expected Result**
Uploaded File should be displayed

**Actual Result**
Uploaded file is not displayed when the user uploads the file

See video - 

https://user-images.githubusercontent.com/5212585/143854728-a53d07b6-2d84-44a1-962a-cfb8422bb7e0.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 5c78c6f

**Comment by daniel-leod** [comment]
@iPiyushPatel Could you please review this issue and tell if you can still reproduce it? Thanks!

**Comment by iPiyushPatel** [comment]
@daniel-leod
Verified on latest develop 08c3368 and it's working fine. Now you can close the issue
Thanks

See video : 

https://user-images.githubusercontent.com/5212585/144980217-bea16669-a228-4c2a-8d46-577b2c981ea6.mp4
