### ISSUE TITLE
G&P | Steps don't display on Goal Details when there is not a current Progress Report

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#1046]
When viewing Goal Details for an Engagement before the first Progress Report, no steps are shown. This is not an issue with Engagements past the end date of the Project as we show the Final progress report.

Can we update this to either show:
- The planned steps without a Progress Report or Progress
- The first Progress Report (just like we continue to show the Final)

<img width="1156" alt="Screen Shot 2021-12-01 at 1 16 23 PM" src="https://user-images.githubusercontent.com/7377802/144307996-2c48508e-e3fa-4745-948f-752328a3d0df.png">
<img width="1082" alt="Screen Shot 2021-12-01 at 1 16 34 PM" src="https://user-images.githubusercontent.com/7377802/144308001-ea96e7cc-c54e-4f6b-a853-9926ddf9a57f.png">
<img width="1045" alt="Screen Shot 2021-12-01 at 1 16 50 PM" src="https://user-images.githubusercontent.com/7377802/144308005-53658333-90ce-4792-a653-0c2bd304edbb.png">

**Comment by sethmcknight** [comment]
@CarsonF any opinions on the approach here?

**Comment by CarsonF** [comment]
Yeah I was just noticing that as well. Showing the chosen steps for the goal on the left sidebar is easy. Can we do that?

**Comment by sethmcknight** [comment]
@CarsonF sounds good to me
