### ISSUE TITLE
Project >Language Engagement > Goal > Progress reports > "Required" message is displayed even "Received" date is entered by user

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1052]
**Roles:** All

**Describe the bug**
Project > Language Engagement > Goal > Progress reports > `Required` message is displayed even `Received` date is entered by user 

**Steps to Reproduce**
1.  Login as a root user
2.  Create a new project 
3.  Create a language engagement in a created project
4.  Add start and end date 
5.  Add goal and click on the created goal 
6.  Click on the Progress for `Report`
7.  Add `PNP` file with `Received Date`

**Expected Result**
`Required` message should not be displayed

**Actual Result**
`Required` message is displayed even date is entered by the user 

See video - 

https://user-images.githubusercontent.com/5212585/146374169-19710df0-1faf-40ab-8057-d67858e85f27.mp4

![image](https://user-images.githubusercontent.com/5212585/146374515-84e36cdb-eb76-4921-8386-87f1446badee.png)

**FYI:**  @ParkeBrown @michaelmarshall 

cord-field# 042b1b4

**Comment by CarsonF** [comment]
Happy to have someone or me dig into this. However, the state of the date field right now is pretty wonky. We have made some compromises on certain flows/situations. Our version is unmaintained, and has been mostly re-written for MUI v5. It's possible that we just leave this and it resolves itself with that upgrade (#867).

Maybe this is specific to this form though. @iPiyushPatel Is there another form we have with a date field that functions differently than what's happening here?

**Comment by iPiyushPatel** [comment]
Hi @CarsonF  
Yes I have another form project `start- end` date field which is working as excepted
Please look into this video and let me know if any questions
Thanks

See video :

https://user-images.githubusercontent.com/5212585/146498408-f4e10b28-62a9-432e-94aa-a3b648c24d6a.mp4
