### ISSUE TITLE
Project > Change Request > Budget details are not updated after editing the change request

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1059]
**Roles:** All

**Describe the bug**
Project > Change Request > Budget details are not updated after editing the change request

**Steps to Reproduce**
1. Login to root user
2. Create a project and change status `Early conversions` to `Active`
3. Create a `Change Request` with `Budget` types
4. Add budget partner in `Partnership`
5. Click on the `Budget` button and add the budget amount
6. Click on the `Change request`  view button and edit the budget details
7. Approved the change request

**Excepted Result**
Budget should be updated when the user edit it from the `Change request`

**Actual Result**
 Budget details are not updated after editing the change request

See video -

https://user-images.githubusercontent.com/5212585/147073053-54fd7bb0-d206-4a3b-ac21-3c8b2a7f2b36.mp4

**FYI:** @ParkeBrown @michaelmarshall

cord-field# 7c3a772

**Comment by CarsonF** [comment]
It changes to $500 if you refresh the page right @iPiyushPatel?

**Comment by iPiyushPatel** [comment]
No, @CarsonF 
Budget value($500) is changed only for `ChangeRequests`, but it's not reflected in Project Details.
