### ISSUE TITLE
Project > Change Request > Getting "Could not find engagement" error when user create a goal from the change request

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1063]
**Roles**: All

**Describe the bug**
Project > Change Request > Getting `Could not find engagement` error when user create a goal from, the change request 

**Steps to Reproduce**

1. Login as a root user
1. Create a new project
1. Change status `Early Conversions` to `Active`
1. Create a change request with `Goal` type
1. Click on the `View` button of change request and add a `Language engagement`
1. Add a goal in the created `Language engagement` and refresh the page

**Expected Result**
Goal should be created without any error message

**Actual Result**
 Getting `Could not find engagement` error when user create a goal from, the change request 

See video -

https://user-images.githubusercontent.com/71218647/147197060-a3d21864-bd37-4a70-ba63-f8c77b65814b.mp4

**FYI**: ParkeBrown michaelmarshall

cord-field# 7c3a772

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466512389) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
Yeah goals/products are not yet changeset aware. This can be seen in the API schema based on whether the type implements the `ChangesetAware` interface.

**Comment by elisabeth-sorrell** [comment]
https://github.com/SeedCompany/cord-api-v3/tree/addChangesetToProducts
