### ISSUE TITLE
Project > Status > Getting "The project YwZ8jub1ADy has never been in any of these previous steps: Active, ActiveChangedPlan" error when a user directly override the status "Early Conversations" to "Finalize Completion"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1073]
**Roles**: All

**Describe the bug**
Project > Status > Getting `The project YwZ8jub1ADy has never been in any of these previous steps: Active, ActiveChangedPlan` error when a user directly override the status `Early Conversations` to `Finalize Completion`

**Steps to Reproduce**
1. Login as a root user
2. Click on the status button
3. Override the status `Early conversation` to `Finalize completion`

**Expected Result**
Status should be overridden `Early Conversations` to `Finalize Completion`

**Actual Result**
Getting `The project YwZ8jub1ADy has never been in any of these previous steps: Active, ActiveChangedPlan` error when a user directly override the status `Early Conversations` to `Finalize Completion`

See video -

https://user-images.githubusercontent.com/5212585/149075288-aaedd882-ec86-4c31-b0d7-05145be15e20.mp4

**FYI**: @ParkeBrown @michaelmarshall

cord-field# 97a6e24

**Comment by CarsonF** [comment]
Fixed by https://github.com/SeedCompany/cord-api-v3/commit/f7ff99f8
