### ISSUE TITLE
createProject > Getting `Cannot read properties of undefined (reading 'filter')` error  when a user creates the project for the first time

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1076]
**Roles:** Administrator

**Describe the bug**
createProject > Getting `Cannot read properties of undefined (reading 'filter')` error  when a user creates the project for the first time

**Steps to Reproduce**
1. Login as root User
2. Create a new project
3. Click on the `Submit` button

**Expected Result**
Project should be created 

**Actual Result**
Getting `Cannot read properties of undefined (reading 'filter')` error  when a user creates the project for the first time

**Note:** 
Error is only reproduced with the `Admin` user and after then refreshing the page it's not reproduced again.

See video -  

https://user-images.githubusercontent.com/5212585/150076277-da27c7d2-cd50-4b79-9231-85fbe67912ef.mp4

**FYI**: @ParkeBrown @michaelmarshall

cord-field# 68f112f

**Comment by CarsonF** [comment]
@iPiyushPatel I cannot reproduce. Have you seen this more than once? Can you open your browser console. It'll have a error message with more info that would be helpful.

**Comment by iPiyushPatel** [comment]
Hi, @CarsonF  Yes I've tried today and observed an Error replicate when we have a fresh database only also no any API error found in the Network tab 

Please find Stack traces and Video reference below. 

**StackTraces:**
```
{
   "data":{
      "createProject":{
         "project":{
            "__typename":"TranslationProject",
            "id":"RtUfX6MkJtR",
            "changeset":null,
            "name":{
               "value":"Project by root 112976",
               "__typename":"SecuredString"
            },
            "createdAt":"2022-01-20T06:38:22.404Z",
            "type":"Translation",
            "sensitivity":"High",
            "departmentId":{
               "value":null,
               "__typename":"SecuredStringNullable"
            },
            "step":{
               "value":"EarlyConversations",
               "__typename":"SecuredProjectStep"
            },
            "projectStatus":"InDevelopment",
            "primaryLocation":{
               "value":null,
               "__typename":"SecuredLocation"
            },
            "estimatedSubmission":{
               "value":null,
               "__typename":"SecuredDateNullable"
            },
            "presetInventory":{
               "value":null,
               "__typename":"SecuredBoolean"
            },
            "modifiedAt":"2022-01-20T06:38:22.403Z",
            "pinned":false,
            "engagements":{
               "total":0,
               "__typename":"SecuredEngagementList"
            }
         },
         "__typename":"CreateProjectOutput"
      }
   }
}

```

See video: 

https://user-images.githubusercontent.com/5212585/150286453-ee23a97b-4dad-443c-81c7-b11340b9bffb.mp4

**Comment by CarsonF** [comment]
It does look like a client error. The _Console_ tab would be more helpful in this case. 
You can see in the top right of DevTools Icons & numbers to indicate the number of messages by type.
You can see that error icon shows up at the same time the error message appears on the UI.
If you click that or the Console tab, you can see the error message in more detail.
If you could paste that error that would be most helpful.

<img width="1079" alt="Screen Shot 2022-01-21 at 6 26 00 AM" src="https://user-images.githubusercontent.com/932566/150527051-20ce36d9-3212-4a20-907b-d78e4af6d4be.png">
<img width="1081" alt="Screen Shot 2022-01-21 at 6 26 58 AM" src="https://user-images.githubusercontent.com/932566/150527044-75c32fc2-a500-4232-9675-d516dabb327f.png">

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
Recently I've checked for this bug but in the latest develop 1ae8d52 I can't reproduce it. please find attached the video

See video:

https://user-images.githubusercontent.com/5212585/150533651-ed99861b-d28c-4897-856e-063554718324.mp4
