### ISSUE TITLE
createProject > LanguageEngagement > createGoal > Selected chapters is not displayed in "Joel" book

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1080]
**Roles:** Administrator

**Describe the bug**
createProject > LanguageEngagement > createGoal > Selected chapters is not displayed in `Joel` book

**Steps to Reproduce**
1. Login as root User
2. Create a new project
3. Open create a project and create languageEngagement
4. Create Scripture Goal with `Joel` book and select chapter `1`, `2`, `3`
5. Click on the `Save` goal button

**Expected Result**
A chapter should be displayed as per availability

**Actual Result**
Selected chapters are not displayed in `Joel` book

**Note:** 
Same issue is reproduced for `Nahum`, `Habakkuk`, `Zephaniah`, `Haggai`, `Titus` books

See video -  

https://user-images.githubusercontent.com/5212585/150313011-d134318f-b558-4d51-87ea-12561477512b.mp4

**FYI**: @ParkeBrown @michaelmarshall

cord-field# 68f112f

**Comment by CarsonF** [comment]
You selected all 3 chapters of Joel. Thus it's the complete book :)

**Comment by iPiyushPatel** [comment]
okay, Got it @CarsonF 
Thanks
