### ISSUE TITLE
Project > Goal > User can add the "Goal" even user has only "Global R" access

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#1127]
**Roles:** Staff member

**Describe the bug**
Project > Goal > User can add the `Goal` even user has only `Global R` access

**Steps to Reproduce**

1. Login as an admin user
1. Create the project and add `LanguageEngagement`
1. Log in as a staff member user
1. Open created project and click on the `Add Goal` button
1. Fill the details and click on the `Save Goal` button

**Expected Result**
User should not be able to add the goal

**Actual Result**
User can add the `Goal` even user has only `Global R` access

See Video -

https://user-images.githubusercontent.com/5212585/132488606-87330550-9ba1-4193-8d57-a84f92432cca.mp4

See Screenshot -

![image](https://user-images.githubusercontent.com/5212585/132488793-2f827497-3ae5-44fb-b9b4-7e824a3aae08.png)

CordAPIV3# f44f1bd
cord-field# d49b012

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466530009) by [Unito](https://www.unito.io)

**Comment by daniel-leod** [comment]
https://github.com/SeedCompany/cord-field/pull/1113/commits/ac304cdc67b0a5a84093b4f8758db0efc63a2c7e will fix this.
