### ISSUE TITLE
Received Date cannot be erased

### ISSUE THREAD

**Issue by atGit2021** [SeedCompany/cord-field#1135]
ticket#6084; After deleting a quarterly report, it's not allowing me to erase the corresponding received date.

**Comment by bryanjnelson** [comment]
![Untitled__2_](https://user-images.githubusercontent.com/1914742/174346491-8aabdce2-d202-4fd5-86dd-f460f6447d8d.png)

The highlighted date above can not be removed.

**Comment by bryanjnelson** [comment]
![Financial_Reports_-_Sayum_Cluster_-_CORD_Field](https://user-images.githubusercontent.com/1914742/174346848-3c6ef355-347b-42b2-a06d-db30cb09e6ff.png)

The date is able to be removed on the popup as shown above, but after clicking "Save" still exists on the main page.
