### ISSUE TITLE
QR | Team Highlights Step

### ISSUE THREAD

**Issue by andrewmurraydavid** [SeedCompany/cord-field#1173]
For the Highlight step, the step will contain a radio button group to select the proper option and a multi line rich text field.

Design link for the Team Highlights: https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/FOR-DEVELOPMENT---Cord-Field?node-id=7707%3A104216

Acceptance Criteria:

- [ ] Step page for all 4 "Roles"
- [ ] List of questions retrieved from the API (or fixture until API is ready)
- [ ] Rich text field (can be a TextField until the EditorJs will be wrapped in FinalForm component)
- [ ] Auto-save functionality
- [ ] Show previous inputs from previous "Roles"

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466485374) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3466485374

**Comment by sherijennings** [comment]
Design updates needed for 10.25 from 
[@Amy Rickwartz](https://seedcompany.slack.com/team/UKW7Z2BEK)
Remove "Save Progress" button at bottom of page, Add "Next" button (right)
remove "successfully" from helper text (saved date, time)
Remove "all reports" navigation
Amy to decide if she wants to keep "previous" on navigation, "Next" on nav bar will stay
Change text on Narrative prompt (in read text box) to Highlight or Team Highlight Prompt
Move "Highlight Prompt" under section title, instructions
Amy to decide if "highlight prompt" bold text will remain in read view text box
