### ISSUE TITLE
QR | PnP Upload Step

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#1178]
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466483052) by [Unito](https://www.unito.io)
┆Link To Item: https://seed-company-squad.monday.com/boards/3451697530/pulses/3466483052

**Comment by sherijennings** [comment]
https://cordfield.com/progress-reports/K1JPylmxZuC
Allow field partners to upload Goals for progress from pnp

**Comment by sherijennings** [comment]
@AmyRickwartz is designing read view, will show input from field partner & upload from field project manager

**Comment by sherijennings** [comment]
View: Allow authorized users (FPM) to view Progress to Goals upload before and after quarterly report submission. 
Allow authorized users to view progress for goals  in Quarterly Narrative Report View
Edit, Allow authorized users to edit FPM Progress to Goals before and after submission
