### ISSUE TITLE
Mobile CordField- Progress Report Text

### ISSUE THREAD

**Issue by sherijennings** [SeedCompany/cord-field#1194]
When viewing progress report summary in CF on mobile, "Progress for Goals" table header text renders on Summary percentage   "box"
First image is view on desktop, 2nd is in prod on mobile, 3rd is in dev on mobile

![Image](https://user-images.githubusercontent.com/113928117/201388402-8c052934-7831-4f12-af07-92b6fb5c0948.png)

![Image](https://user-images.githubusercontent.com/113928117/201389134-c2a18350-3e54-4162-8147-3dc3c3d8e759.jpg)

![Image](https://user-images.githubusercontent.com/113928117/201389156-c08edea5-c4e2-4efa-8584-2c03e38014c9.jpg)

Issue will be considered resolved when text placement appears above table and not encroaching on other text on page.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3512868267) by [Unito](https://www.unito.io)

**Comment by willdch** [comment]
I was unable to reproduce this bug.  I used the chrome dev-tools emulator to attempt to reproduce the issue on many different mobile screen sizes but I was unable to reproduce the bug.  After speaking with Carson we think it might have been a caching problem with the browser of the device the bug occurred on.
