### ISSUE TITLE
People List Scene

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#127]
Depends on #95 #111

**Comment by jmc637** [comment]
Hi, I made the person card for this but then realized it was blocked. I'll stop working on this now but whoever works on this issue when it become unblocked doesn't have to make the person card.

**Comment by CarsonF** [comment]
After discussing with @prutherford we are going to skip this for initial release. Patrick says the current list of "all people" is not used by field at all. He wants to do 1+ lists that are relevant to the user. Which can come later.
