### ISSUE TITLE
[Design] Partners Detail View

### ISSUE THREAD

**Issue by prutherford** [SeedCompany/cord-field#132]
Design a Partner Details View for CORD Field 3. The view should allow for displaying, editing, and linking to information as needed.

The view should include the following information in rough order of importance:

* Partner Name

* Global Innovations Client - this is a flag/tag
* Status - this is a flag/tag of Active or Inactive

* PMC Entity Code - this is a 3 character code used to denote how funds are transferred to the organization through the PMC System (ie. TSC)
* Location - this is the location where the organization's primary business office is located.

* Partner Type(s) - this specifies which Types can be selected when managing a Partnership. A Partner could have none, all, or any combination of the available options. [Funding, Managing, Technical, Resource, Impact]
* Financial Reporting Type - if the Partner can hold the Type of Managing, then we will capture and display this field specifying how they can provide financial reports for a Project. This is a required field, but they can select either or both of the reporting types [Funded or Field Engaged]

* Address - this is the primary business address for the partner [text field for now]
* Point of Contact - this is the person who should be contacted if trying to contact the organization [link to a person in CORD Field]

* Relationships - this is a list of the cards for each entity associated with a given Partner [Projects, Languages, People]

**Comment by sethmcknight** [comment]
Designs will be implemented in #372
