### ISSUE TITLE
QR- Add start report button

### ISSUE THREAD

**Issue by sherijennings** [SeedCompany/cord-field#1332]
Add start report button after user selects quarterly report from progress reports list, next to (right of) skip report button
After selecting button, report drawer opens

![Image](https://user-images.githubusercontent.com/113928117/205695906-47451940-994c-4c12-907e-5c6652ad6dd7.png)

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3622109397) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
I'd have it as a button on the edit drawer page instead. It could be shown instead of all other content.

**Comment by CarsonF** [comment]
Closed #1342
