### ISSUE TITLE
QR- Add Language engagement summary text box

### ISSUE THREAD

**Issue by sherijennings** [SeedCompany/cord-field#1333]
Add sm/med text box to UI, DB & API for Language engagement summary right "language engagement" text. Should fit 4-5 sentences

![Image](https://user-images.githubusercontent.com/113928117/205712193-89eb578b-f84a-4c0c-a389-f942a785d697.png)

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3622109121) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
This sounds like a rich text `description` field. Feel free to add to API as well @andrewmurraydavid

**Comment by CarsonF** [comment]
@sherijennings who can view/edit this field? Same as anyone who can view/edit the engagement or does this need to be called out specifically for certain roles?
