### ISSUE TITLE
Simple Project List

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#153]
![Screen Shot 2020-05-05 at 10 26 18 AM](https://user-images.githubusercontent.com/932566/81084008-f1340180-8eba-11ea-9edb-cda650698593.png)
https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=1%3A3

## Requirements

- [ ] `Projects` component acting as sub-router (and parent styling - maybe none)
  - `Organizations` could be used as an example.
- [ ] `ProjectList` component connecting API to a list of `ProjectListItemCard`s.
  - The list component/route should be at `/projects`.
  - List does not need to handle pagination, sorting, or filtering.
  - [ ] Page Title
  - [ ] Stub _Sort Options_ and _Filter Options_ buttons.
          Use the `outline` variant - we can tweak it later to make it look more like designs.
  - [ ] Display list total
- [ ] Make a `ProjectListItem` GQL fragment
- [ ] Update `ProjectListItemCard` to take a single `project` prop of type `ProjectListItemFragment`

**Comment by CarsonF** [comment]
Actually try using a `<Card variant="outlined" /> for sorting and filter options. Will need to use `<CardActionArea />` inside.

**Comment by aaronkchsu** [comment]
Do you mean sorting and filter button should be inside this card?
