### ISSUE TITLE
Field Overview Card - Loading State, etc

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#188]
## Requirements
- [ ] `loading` boolean prop makes sense here since it's independent of an API shape
- [ ] This means other props need to be made optional and handle that
- [ ] Implement Skeleton's when loading is true
- [ ] Change `updatedAt` to be `DateTime | string` and to be formatted with `useDateTimeFormatter()` hook.

**Comment by richardgirges** [comment]
I wonder if we should take all of the required props and put them inside of a nested object. e.g.:

```typescript
interface FieldOverviewData {
  className?: string;
  title: string;
  value: string;
  icon: ReactElement<SvgIconProps>;
  updatedAt: DateTime;
  to: To;
  viewLabel: string;
}

export interface FieldOverviewCardProps {
  data?: FieldOverviewData;
  loading: boolean;
}
```

This will allow us to ensure required properties are referenced without the need for null checks or non-null assertions.

**Comment by CarsonF** [comment]
A loading boolean looks clean when using component but yeah we want those to be exclusive.
You could try this too:
```tsx
import { MergeExclusive } from 'type-fest';

type Props = MergeExclusive<{ loading: true }, { loading?: false, title: string, ... }>;
```
I don't remember if that plays nicely with JSX, but could be worth a shot.

Otherwise I would say yeah let's have a nested `data` prop that's optional. And since we have that there's not really a need for the loading prop as a missing `data` value indicates that.
