### ISSUE TITLE
ProjectMembersList Scene

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#208]
Depends on #207 

![Screen Shot 2020-05-26 at 11 12 09 AM](https://user-images.githubusercontent.com/932566/82924312-c41ac200-9f41-11ea-8af5-b668f16cc414.png)
https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=2236%3A0

- However, we will not be grouping by roles, like `Directors`. We'll only show one person with multiple roles.
- url: `/projects/{id}/members`
- edit button can be stubbed, but it will be a dialog in the future.
- The add button functionality can be stubbed. But Patrick asked that the text next to be icon button be clickable as well.

**Comment by aaronkchsu** [comment]
Waiting for ProjectMemberCard and I will be back to this ticket with completion of file service api update.
