### ISSUE TITLE
Update Register User for new API

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#224]
Following https://github.com/SeedCompany/cord-api-v3/issues/444

Our register user code needs to be updated for API changes. I think for this it's just changing the gql mutation. Input is the same.

**Comment by glassblowerscat** [comment]
FE work is basically done here, but the API branch has conflicts with `master`, so not sure my PR will work with whatever the API actually ends up being. Whenever that API work is done this can be tested and taken out of draft state.
