### ISSUE TITLE
Currency Field

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#225]
A new form field that is for currency.

Previously implemented on corporate website [NumberFormatInput](https://github.com/SeedCompany/website-v3/blob/824eb75b69896ce53cf50a6fd8164eabb8694771/src/components/Shared/Common/NumberFormatInput.tsx), [CurrencyInput](https://github.com/SeedCompany/website-v3/blob/47a7b11ee4e2dc1c813d9ef50eb772eefc75adf2/src/components/Donate/DonateCard/CurrencyInput.tsx), [Amount](https://github.com/SeedCompany/website-v3/blob/d6851b50729a4b9533601742fe7a7f74056f91ea/src/components/Donate/DonateCard/Amount.tsx#L105).
I know it's private :/ It's using `react-number-format` library. Feel free to use that or another implementation. I've seen some hook versions as well. I think the MUI date picker library uses one.

It should be just be able to be extended from our `TextField`, just like Email or Password Fields.

**Comment by CarsonF** [comment]
@richardgirges Maybe you can pick this up since you have access to those links?

**Comment by richardgirges** [comment]
Sounds good @CarsonF !

**Comment by CarsonF** [comment]
Closed with #246
