### ISSUE TITLE
Budget Scene

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#226]
- [x] url: `/projects/{id}/budget`
- [ ] data pulled from `project.budget`
- [x] I'm guessing an MUI table would be best here
  - https://material-table.com/ might be a good resource here to allow for inline editing
  - Only the amount column is possibly editable. Each `BudgetRecord` amount should check `record.amount.canEdit` to allow editing.
  - Each record (row) will need to be saved individually
  - [x] This could be a separate `RecordsTable` component in the scene folder
- The budget has a `total` property but it might be better to calculate based on record amounts since they are editable here. Another example of a "side effect" from the API. Or open to using total working with Apollo cache. If it would help if the API returned the budget from that mutation then we can make that happen as well.
- We have a `useCurrencyFormatter` hook too, which will probably be useful.

Here's screenshot from v2 as an idea:
![Screen Shot 2020-06-05 at 4 56 42 PM](https://user-images.githubusercontent.com/932566/83927588-f94dbe00-a752-11ea-8c81-19d03248e5ab.png)
It should have column headers, fiscal year displayed better, amount formatted and right aligned.

**Comment by glassblowerscat** [comment]
This data is not actually query-able right now; the back end returns an error. The FE work is mostly done, but I’m pretty sure some adjustments will need to be made once I see exactly what the returned data looks like.

**Comment by glassblowerscat** [comment]
Still blocked on this, although for different reasons than I first reported. Waiting on  https://github.com/SeedCompany/cord-api-v3/issues/573 and https://github.com/SeedCompany/cord-api-v3/issues/574
