### ISSUE TITLE
Codegen GraphQL query const strings

### ISSUE THREAD

**Issue by richardgirges** [SeedCompany/cord-field#234]
We want graphql-codegen to export a const string representing every single GraphQL Query Operation name.

* Investigate any potential plugins that may provide this functionality out of the box
* Investigate potentially rolling our own custom plugin for producing this behavior

Writing your own Codegen plugin: https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin

## Additional Details:

As an example, the following query:

```graphql
query FooList {
  foo {
    id
    name
  }
}
```

...should allow you to import a `const` by the name of `FooListOperation` or something of that nature:

```typescript
import { FooListQuery } from './foo.generated';

console.log(FooListQuery); // "FooList"
```

This will allow us to have type-safe operation names to pass into our mutations for cache-invalidation upon refetching:

```typescript
    const res = await createFoo({
      variables: { input },
      refetchQueries: [FooListQuery],
    });
```

**Comment by CarsonF** [comment]
https://graphql-code-generator.com/docs/plugins/named-operations-object
