### ISSUE TITLE
File Upload / Drag & Drop

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#259]
First step is research the best library(ies) to use. We want one that works well with TypeScript, preferably react hooks / modern react API, and easy to integrate with Material UI.

To integrate with our File API:
 - `requestUpload` mutation
 - post file to given url from above
 - call `createFileVersion` after that with `id` from first call

I don't have a lot of this laid out from a frontend perspective, so bare with me.

**Comment by glassblowerscat** [comment]
Additional requirements after some research/conversation with Carson:

- Using `react-dropzone`
- Need to support multiple files at once
  - User should be able to drag multiple files in at once
  - "Pending" state between "submit" and "upload". Sometimes this will be automatic, but we may want to support letting the user add multiple files before uploading all of them at once
  - Start with serial upload of files; consider parallel later
- Upload Progress UI
  - Persistent across pages, so we'll need a Context for this
  - Start with just a Snackbar showing a simple "1 of 3 uploaded"
  - Later this should look similar to the Google Drive upload UI:
    - draggable modal
    - collapsable
    - closable
    - lists filenames with a status/progress bar for each
    - toolbar for dragging/collapsing/closing/???

More detail on upload API:

1. Request temp upload URL
2. PUT request to returned URL with `Content-Type` set to file's MIME type
3. Varies depending on use

So we can abstract the first two steps, but we'll need to pass in a callback with any required input for the third step.
