### ISSUE TITLE
Verses Field

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#270]
![Screen Shot 2020-06-24 at 3 04 28 PM](https://user-images.githubusercontent.com/932566/85622163-0d872b80-b62c-11ea-9eea-1abf5ff7bb21.png)

This is going to be a complicated component. 
- [x] Needs to provide UI as show above. MUI's Autocomplete could probably get us pretty close there. We probably won't provide any autocomplete options though given how customizable input can be
- The current book will be given to field
- [x] Input syntax needs to be validated. Valid:
  - `{chapter}`
  - `{chapter}-{chapter}`
  - `{chapter}:{verse}`
  - `{chapter}:{verse}-{verse}`
  - `{chapter}:{verse}-{chapter}:{verse}`
  - Since only numbers, `:`, and `-` are valid input it would be good to use the `FormattedTextField` somehow
- [x] Input string needs to be parsed to an absolute verse range
  - _absolute verse_: verses are per chapter per book. To make it easier to keep track of we are **flatting** that 3-level tree into 1-level. So Genesis chapter 1 verse 1 is 0 as the starting point. Gen 1:2 is 1. Gen 2:1 is 31 since Gen chapter 1 has 31 verses. Exodus 1:1 starts after the sum of all the verses in Genesis. etc.
  - This makes it easy to represent:
      ```tsx
      interface AbsoluteVerseRange {
        start: number;
        end: number;
      }
      ```
   - A library could be found that has this data (number of chapters & verses per book/chapter). If not we can just define ourselves.
   - Parse logic follows:
      - `{chapter}` -> {chapter} verse 1 to {chapter} {last verse in chapter}
      - `{chapter}-{chapter}` -> {first chapter} verse 1 to {second chapter} {last verse in chapter}
      - `{chapter}:{verse}` -> {chapter} {verse} to {chapter} {verse} (single verse)
      - `{chapter}:{verse}-{verse}` -> {chapter} {first verse} to {chapter} {second verse}
      - `{chapter}:{verse}-{chapter}:{verse}` -> {first chapter} {first verse} to {second chapter} {second verse}
- [x] The input also needs to be validated. This is an extra step after being syntactically correct.
  - For example, given book Genesis, this input `1:32` is syntactically correct, but it's invalid since Genesis chapter 1 only has 31 verses.
  - For this reason it might be good to have an intermediate shape to split parsing logic and conversion to absolute verse range logic.
    ```tsx
      interface VerseRef {
        book: string;
        chapter: number;
        verse?: number;
      }
      interface RangeRef {
        start: VerseRef;
        end: VerseRef;
      }
      ```
- [x] An absolute verse range needs to be formatted to a string. This is just the inverse of the parsing logic. This will probably need to be used in other places in our UI so it should be separated from this field file.

**Comment by blakekrammes** [comment]
@CarsonF, I've been looking at https://github.com/davewasmer/biblejs because it provides absolute verse numbers based on a reference string like "Exodus 2:4". Few issues: it's been archived, no TS, and no validation for references. You could do "Exodus 2:4000" and it wouldn't blink. 

I'm not seeing a lot of other options that provide absolute verse numbers. We could copy over their book, chapter and verse mappings and implement our own validation logic. 

I can keep digging around and see if there are any other alternatives.

**Comment by CarsonF** [comment]
That could be a good starting point for our own logic. I don't really expect anyone to do this in a way that we need. Also the validation isn't hard logic - the scripture mapping will add the same bundle size either way (library or our own src).

**Comment by blakekrammes** [comment]
Can I take on the reference string ––> AVN (absolute verse number) and AVN ––> reference string logic? Should that be a separate ticket?

**Comment by CarsonF** [comment]
Sure. That intermediate shape will probably be helpful too.

First step is handling user input
```tsx
interface ScriptureReference {
  book: string;
  chapter: number;
  verse?: number;
}
type Range<T> = { start: T, end: T };
type RawScriptureRange = Range<Nullable<ScriptureReference>>>;

// This should handle partial input as well which is why `start` and `end` are nullable.
function parseScriptureRange(str: string): RawScriptureRange
```

From there we need to validate what they've typed
```tsx
type ScriptureRange = Range<Required<ScriptureReference>>>;
// This could throw an error we can show in UI or return the completed range
// errors like "Matthew only has 28 chapters"
function validateScriptureRange(range: RawScriptureRange): ScriptureRange;
```

At this point we'll know the range is valid so it can be safely converted to a verse range.
Also the opposite which will come from the API.
```tsx
type VerseRange = Range<number>;
function scriptureToVerseRange(range: ScriptureRange): VerseRange;
function verseToScriptureRange(range: VerseRange): ScriptureRange;
```

From there we can format to a string
```tsx
function formatScriptureRange(range: ScriptureRange): string;
```

**Comment by blakekrammes** [comment]
Is the reason it needs to handle/check partial input because we want to send an error if someone tries to input "Exodus: 1:400"?

**Comment by CarsonF** [comment]
Really just to keep those pieces of logic separate / single responsibility. We'll probably use the validation fn in FF validators where the parsing will be more in the formatted text section. Trying to not assume anything about usage since we don't know exactly how it will work yet.

**Comment by blakekrammes** [comment]
> First step is handling user input

Step one is done, starting step two

> From there we need to validate what they've typed

**Comment by blakekrammes** [comment]
The code for parsing and formatting is in review. I can start working on the UI.
