### ISSUE TITLE
ToggleButtonOption

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#271]
![Screen Shot 2020-06-24 at 3 45 52 PM](https://user-images.githubusercontent.com/932566/85625905-cef46f80-b631-11ea-8e37-99179e4d4581.png)

The above works logically just like `CheckboxesField`. Which means we could probably just substitute the `CheckboxOption` for a `ToggleButtonOption` component.

- [ ] Create the `ToggleButtonOption` component.
- [ ] Update the app theme to make the MUI `ToggleButton` look like UI above

**Comment by richardgirges** [comment]
One clarification point @CarsonF  - are we going to entirely replace `CheckboxesField`? Or make a new component called `ToggleButtonOption` that's functionally identical to `CheckboxesField` and visually unidentical?

**Comment by CarsonF** [comment]
I was thinking 

```tsx
<CheckboxesField>
  <ToggleButtonOption />
</CheckboxesField>
```

Really what I would like to do is combine radio & checkboxes into one with an `exclusive` option and maybe a variant prop to switch between this and radio/checkbox. But another day...
