### ISSUE TITLE
File List Table Card

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-field#297]
- [ ] Displays a directory's children
- I imagine it being in a card
- I think we talked about removing the `type` column and just adding a icon before the file name based on the `node.category`.

Screenshot from v2
![Screen Shot 2020-07-07 at 2 55 46 PM](https://user-images.githubusercontent.com/932566/86835698-17fce880-c062-11ea-9aa7-cfd60db22e9c.png)

**Comment by glassblowerscat** [comment]
Popup menu contents

![image](https://user-images.githubusercontent.com/728777/87209688-cdd56a80-c2e0-11ea-8634-bbf8a1add129.png)
