### ISSUE TITLE
Project list is not refreshed on logout/login for new logged in user until page is refreshed

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#305]
**Describe the bug**
UI > Project list is not refreshed on logout/login for new logged in user until page is refreshed

**Steps to Reproduce**

1. On Cordfield UI e.g. http://localhost:3001/projects, Login as User 1
2. Logout 
3. Login as User 2 who has different number of projects.

**Expected Result**
Projects details is correct for logged in User 2.

**Actual Result**
Previously logged in user's projects are shown till page is refreshed . See video - https://www.awesomescreenshot.com/video/307624?key=ce775251e027053deaa7765717570abb

CordFieldUI# 5d92772
CordAPIV3#1caff78

**Comment by CarsonF** [comment]
We should probably clear all cache on login. Agree @richardgirges?

**Comment by richardgirges** [comment]
Yep. Two options here: 

1. hard load on login (hacky but effective way of resetting all caches and state)
2. Reset Apollo cache manually

**Comment by CarsonF** [comment]
Hard reload is never a solution :wink:

**Comment by richardgirges** [comment]
@CarsonF going to take a crack at this
