### ISSUE TITLE
Registration page/Invalid User Entry - No error message and Unable to Sign Up after Correcting

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-field#311]
User entered a valid email address and single characters in all other fields. Upon hitting Sign Up button, user account was expectedly not created. However, error messages didn't appear. When fields are corrected, user is unable to hit the Sign Up button.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/07ea85ef-a0e2-4561-99f5-256da2133501)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/84777b5e-b56d-427e-9453-d4f0c3872418)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/5ccf9ad1-0a68-4006-8d16-b2f8646e56e9)

**Comment by frankyma** [comment]
Approach:

1. Match the text field names with the api field names
2. Show display first name and display last name fields
3. Enforce minimum of 2 chars for name fields

**Comment by CarsonF** [comment]
@reneepe I believe this is fixed now

**Comment by frankyma** [comment]
Closing because fixed
