### ISSUE TITLE
Language | Pronunciation Guide

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#318]
Add an optional field to Languages called 'Pronunciation Guide'.

This field should be optional and tied to the Display Name. This will provide a place for users to input and view the pronunciation of Language names.

**Comment by CarsonF** [comment]
Why the display name and not the real name?

**Comment by sethmcknight** [comment]
The display name is what will be used/shared publicly. For Low-Sensitivity Languages this will be the same as the Ethnologue Name, but for Medium and High it will be a psuedonym.

**Comment by frankyma** [comment]
Blocked until BE opens up pronunciation field

**Comment by frankyma** [comment]
Implemented on the Language Detail view

**Comment by CarsonF** [comment]
@frankyma can you rename what we show to include the word "guide"?

**Comment by frankyma** [comment]
Copy
