### ISSUE TITLE
Retry NoSession errors

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#327]
We when get a `NoSession` error code we should re-run the session query and then retry the current query/mutation again. 
This needs to be done with an ApolloLink in ApolloProvider.tsx file.

**Comment by richardgirges** [comment]
10-4. It shall be done @CarsonF

**Comment by richardgirges** [comment]
@CarsonF Should we blindly re-run the session query? Do we care about the result of the query? e.g. what happens if the query fails?

**Comment by CarsonF** [comment]
Maybe we could keep the original error and if the session query fails just throw the original one?

**Comment by richardgirges** [comment]
Makes sense, will do!
