### ISSUE TITLE
Create Language Window > Invalid Data Entered > Incorrectly Displayed and Formatted Error Messages

### ISSUE THREAD

**Issue by reneepe** [SeedCompany/cord-field#342]
In the Create Language's window, entering invalid data triggers 3 of the same error messages to display. The error messages aren't displayed by the field that they apply and they aren't formatted correctly.

**Steps to Reproduce**
1. Go to FE
2. Log into an account
3. Click on 'Create New Item'
4. Click on 'Language'
5. Enter data reflected in screenshot below
6. Click on 'Submit'
7. See error

**Expected Results**
A single error message should be displayed by the field that contains the invalid entry. Each message should clearly state the error.

**Actual Results**
Three of the same error messages were displayed. The error messages aren't displayed by the fields that they apply and they aren't formatted correctly.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/1dee912b-ff4d-43ba-a571-5835589045db)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/a2e8ebd7-71a3-40c9-a6c4-4a3c8c9e6173)

Desktop:
- OS: Windows 10 Pro
- Chrome
- Version 1903

**Comment by CarsonF** [comment]
Fixed with #333

**Comment by reneepe** [comment]
@CarsonF Should the error messages appear like below?

![image](https://user-images.githubusercontent.com/38309285/88003307-916cf000-cad2-11ea-9e1b-657f65a35184.png)

**Comment by CarsonF** [comment]
This looks like a old version. Is this locally?

**Comment by frankyma** [comment]
@reneepe Can you confirm if this ticket is still relevant?  I just tried to repo on v3 and didn't get any errors.  Also the form UI looks different from both screenshots.
