### ISSUE TITLE
Project Card Displays 0 Engagements when Engagements Exist

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#370]
Each _Project Card_ should display the total number of Engagements that are a part of the Project.

Currently all _Project Card's_ display 0 Engagements, regardless of the number of Engagements that exist.

**Comment by CarsonF** [comment]
@frankyma does #313 fix this? I know we had those props commented out for a while, but I saw them re-enabled somewhere.

**Comment by frankyma** [comment]
No 313 doesn't touch project cards
