### ISSUE TITLE
Display/Edit Additional Partner Information

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#372]
On the Partner Details view, we need to display and edit the following information:

- Global Innovations Client [was Second Line of Ministry/2LOM Flag]
- PMC Entity Code [was called SIL Entity Code]
- Status [Active/Inactive]
- Partner Type(s) [Funding, Managing, Technical, Resource, Impact]
- Financial Reporting Type [if a Managing Partner; Funded or Field Engaged]
- Location
- Address [text field for now]
- Point of Contact [link to a person]
- Relationships [People, Projects, Languages]

**Comment by CarsonF** [comment]
This is a lot of new information that the API needs to support first.

**Comment by CarsonF** [comment]
> * Global Innovations Client [was Second Line of Ministry/2LOM Flag]

This is a boolean (yes/no) flag?

> * PMC Entity Code [was called SIL Entity Code]

What's the format?

> * Status [Active/Inactive]

What does active represent? What does inactive represent? I'm assuming there's remove in the future for another state representing something else.

**Comment by sethmcknight** [comment]
> > * Global Innovations Client [was Second Line of Ministry/2LOM Flag]
> 
> This is a boolean (yes/no) flag?
> 
Correct, this is a boolean flag.

> > * PMC Entity Code [was called SIL Entity Code]
> 
> What's the format?
> 
Three capital letters (e.g. AAA)

> > * Status [Active/Inactive]
> 
> What does active represent? What does inactive represent? I'm assuming there's remove in the future for another state representing something else.
Active represents an organization we are currently working with in some capacity or have plans to work with in the future.
Inactive represents an organization that we have worked with or had plans to work with in the past but are no longer working with and have no future plans to work with.

**Comment by sethmcknight** [comment]
blocked by https://github.com/SeedCompany/cord-api-v3/issues/982

**Comment by CarsonF** [comment]
Blocked by #511
