### ISSUE TITLE
UI Shadows are Too Heavy

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#375]
The shadows in the UI should be lighter, check the design system here:

https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=14%3A0

**Comment by CarsonF** [comment]
We are using standard Material Design "elevation" levels. I don't want to bother with completely customizing that right now. Happy to change the default elevation though.

Here's what the design specs are for the default elevations of all components https://material.io/design/environment/elevation.html#default-elevations

**Comment by sethmcknight** [comment]
Hold - Revisit after migration complete.
