### ISSUE TITLE
Move Tag Pills on Language Details

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#377]
The blue Tag Pills on the Language Details page should be moved to their own line beneath Sensitivity.

**Comment by CarsonF** [comment]
The reason I kept them on the same line is that we don't show them if the properties are false. If they were on their own line the content would shift up and down while loading because we don't know whether that extra row will exist before the data is loaded.

**Comment by CarsonF** [comment]
What we could do is keep the row height the same regardless of whether there are chips to display or not. But it might look weird to have that extra empty spacing.

**Comment by sethmcknight** [comment]
Revisit post-migration
