### ISSUE TITLE
Resize page tuck

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#378]
On our pages the main content scrolls underneath a top nav section (Search & Right Menu).

The tuck where the content scrolls under needs some padding added beneath the Right Menu.

Check designs here: https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=14%3A0

<img width="1204" alt="Screen Shot 2020-08-11 at 8 49 11 AM" src="https://user-images.githubusercontent.com/7377802/89905453-d2c35d80-dbaf-11ea-90e5-0430e2033427.png">

**Comment by CarsonF** [comment]
Yeah it's a little weird because the search is shorter than the toolbar. We can add margin here but it will further push the main content down the page and it will look different not being scrolled down at all.

**Comment by sethmcknight** [comment]
Patrick said to go ahead and add the spacing, don't worry about the additional space between search and name.
