### ISSUE TITLE
Language Details | Move Projects In-Line

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#379]
On the Language Details page, we need to move the Projects list in-line with the rest of the content.

We can just bump this over underneath the Locations section.

**Comment by CarsonF** [comment]
I believe it will right now if the window is narrow enough. Is there a reason we don't want to utilize more of the screen space?

**Comment by sethmcknight** [comment]
From Patrick:
"If we use a Card, always align left. Other data we can split left/right."

**Comment by frankyma** [comment]
> I believe it will right now if the window is narrow enough. Is there a reason we don't want to utilize more of the screen space?

@CarsonF we don't have the responsive design built in. See how in my screenshot the window is narrowed but the cards don't stack.
<img width="541" alt="Screen Shot 2020-08-12 at 2 22 09 PM" src="https://user-images.githubusercontent.com/43487134/90069528-472cf800-dca7-11ea-8a23-ef9ade195af3.png">.  checking our code we don't have a md breakpoint set (it's all xs={6} on the grid).

**Comment by CarsonF** [comment]
Ok np. Let just drop it below as Patrick requested.
