### ISSUE TITLE
First Scripture Flag Validation

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#39]
We need to validate that the 'First Scripture Flag' has not been selected for a prior Language Engagement before displaying the input and allowing a user to select it for a new Language Engagement.

It would probably be good to add a 'First Scripture' or 'Has Scripture' field to a Language that is set based on the Language Engagements if not manually set.

- Language has a boolean that identifies if it has scripture that isn't recorded in CORD Field.

**Comment by CarsonF** [comment]
On the UI side we need:

- [ ] On the edit dialog, a checkbox `hasExternalFirstScripture` labeled something like "Was this language's first scripture was produced outside of CORD?" (maybe the label is shorter and that longer description is a tooltip)
  - Ideally this is disabled if the any of the engagements have firstScripture=true, but I'm ok falling back to the API to do the validation for this.

- [ ] On the detail scene, a "first scripture" section/field that indicates either:
  - the engagement implementing the first scripture
  - first scripture was external/outside of CORD
  - missing, the language doesn't have first scripture yet

I just made this up off the top of my head so I'm sure it will be subject to design changes (as this whole page is)

**Comment by glassblowerscat** [comment]
> * [ ]  On the edit dialog, a checkbox `hasExternalFirstScripture` labeled something like "Was this language's first scripture was produced outside of CORD?" (maybe the label is shorter and that longer description is a tooltip)

@Carson I notice that Zayar updated the API to perform this check, but he didn't add the `hasExternalFirstScripture` field to `CreateLanguageEngagementInput` or `UpdateLanguageEngagementInput`. Did you change your mind about doing it this way, and we're just going to let the user select `firstScripture` regardless, or do we need an additional API update?

**Comment by CarsonF** [comment]
`hasExternalFirstScripture` is for `Language` not `LanguageEngagement` - it is on Language's create/update mutations.

I think my vote right now is to just let the API enforce it. We can tweak the UI message if needed.

Showing the first scripture boolean on the detail page needs us to be smart though - we have to handle those 2 ways it could be "true" else "false".

**Comment by glassblowerscat** [comment]
> Showing the first scripture boolean on the detail page needs us to be smart though - we have to handle those 2 ways it could be "true" else "false".

@CarsonF From what I can tell, we don't have a  query that will give us the language with its engagements. This means in order to check whether any engagement for this language has the `firstScripture` flag, we will have to run multiple queries on the Language Detail scene:

1. Initial `language` query: gets list of Projects with an engagement for this Language
2. For each project, run a 2nd query for list of its Engagements
3. Check whether any of the returned Engagements are for this Language
4. Check whether any of the Engagements for this Language have `firstScripture: true`

That seems very suboptimal. Are we planning on updating the API to return this data in some existing query?

**Comment by CarsonF** [comment]
```gql
query {
  language(id: "") {
    hasExternalFirstScripture {
      value
    }
    projects {
      items {
        engagements {
          items {
            id
            ... on LanguageEngagement {
              firstScripture {
                value
              }
            }
          }
        }
      }
    }
  }
}
```
It's definitely not the best query, but possible with one call...

**Comment by glassblowerscat** [comment]
> ```graphql
> ```graphql
> query {
>   language(id: "") {
>     hasExternalFirstScripture {
>       value
>     }
>     projects {
>       items {
>         engagements {
>           items {
>             id
>             ... on LanguageEngagement {
>               firstScripture {
>                 value
>               }
>             }
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> 
> It's definitely not the best query, but possible with one call...
> ```

Blahhhhh sometimes I'm so bad at GraphQL
