### ISSUE TITLE
Make edit/update wording consistent

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-field#455]
Currently for our update actions, some say edit (eg Langauge) and some say Update (e.g. project).  Need to make this all consistent.  This includes the UI wording, file names, and function/variables

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466662717) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
@prutherford @AmyRickwartz @sethmcknight Thoughts?

**Comment by prutherford** [comment]
“Edit” is the act of changing something, “Update“ would be the act of saving edited information.

That help?

**Comment by frankyma** [comment]
We need to choose either word on all these "change" actions
![Screen Shot 2020-09-16 at 11 07 40 AM](https://user-images.githubusercontent.com/43487134/93375432-0035a380-f80d-11ea-9af3-8835c2a03e92.png)
![Screen Shot 2020-09-16 at 11 08 11 AM](https://user-images.githubusercontent.com/43487134/93375438-0166d080-f80d-11ea-9224-798d6a3acc22.png)
![Screen Shot 2020-09-16 at 11 08 17 AM](https://user-images.githubusercontent.com/43487134/93375439-0166d080-f80d-11ea-9778-609076cd56af.png)
![Screen Shot 2020-09-16 at 11 07 30 AM](https://user-images.githubusercontent.com/43487134/93375442-01ff6700-f80d-11ea-8a3d-16109a639d78.png)
![Screen Shot 2020-09-16 at 11 07 20 AM](https://user-images.githubusercontent.com/43487134/93375443-0297fd80-f80d-11ea-967d-0f2b922ed4bf.png)

**Comment by AmyRickwartz** [comment]
Seems like you Edit would be more universal for both. Would you use "Update" instead where the "Save" button goes? So instead of saying "Save" you say "Update"?

**Comment by frankyma** [comment]
I think Save can stay save as long as the title is clear (Update/Edit).  Once you guys/gals of design decide on either word we'll make the rest consistent.

**Comment by frankyma** [comment]
@AmyRickwartz and I just talked and agreed on **Edit**.
