### ISSUE TITLE
Project detail card size

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#466]
The top row height does not need to expand to the size of the second row.

![Screen Shot 2020-09-17 at 7 38 57 PM](https://user-images.githubusercontent.com/932566/93541970-7cb7a780-f91d-11ea-9f90-c2045db3e5de.png)

**Comment by CarsonF** [comment]
Regressed in #459

**Comment by glassblowerscat** [comment]
@CarsonF What's the behavior we're looking for? We were trying to solve [this behavior](https://github.com/SeedCompany/cord-field/issues/453). Is it that we just want to make sure that cards that have an "action" row, such as with an Edit button in it, are the same height as each other, but not necessarily the same height as cards without the action row?

**Comment by CarsonF** [comment]
Yeah both rows are independent.
