### ISSUE TITLE
Display Project Sensitivity on Related Scenes

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#471]
Display the Project Sensitivity on each scene related to the Project:

- Budget Details
- Files
- Team Member Details
- Partnership Details
- Engagement Details

**Comment by CarsonF** [comment]
@sethmcknight on the engagement details the sensitivity should be the language's right?

**Comment by CarsonF** [comment]
Seth said project on zoom

**Comment by CarsonF** [comment]
@AmyRickwartz @prutherford Looking for input on what this should look like.

Currently @glassblowerscat displays it similar to how we display other properties.
![Screen Shot 2020-10-02 at 3 05 04 PM](https://user-images.githubusercontent.com/932566/94965266-ccbb7000-04c0-11eb-990e-227dde6c1ecf.png)

I'm wondering if we should try to be consistent with the way we display it in other places
![Screen Shot 2020-10-02 at 3 06 41 PM](https://user-images.githubusercontent.com/932566/94965345-ec529880-04c0-11eb-8fbc-3924e69fadb5.png)

What about the location of it below the breadcrumbs? Maybe inside of a popover that displays while hovering over project name would be better? That would also allow other important to be shown at a glance.

GitHub does this when you over over issue references (the `#497` link in this screenshot)
![Screen Shot 2020-10-02 at 3 08 55 PM](https://user-images.githubusercontent.com/932566/94965523-47848b00-04c1-11eb-854a-bf6e817e2cc4.png)

**Comment by prutherford** [comment]
How you guys stacked sensitivity makes everything else inline look broken.

What is in the Figma prototype?

**Comment by CarsonF** [comment]
@prutherford Stacked how? If you are referring to the budget page, this is a new request. It isn't in Figma.

If you are referring to the small screenshot of sensitivity that's how it is in [Figma](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=1524%3A14).

**Comment by AmyRickwartz** [comment]
> @AmyRickwartz @prutherford Looking for input on what this should look like.
> 
> Currently @glassblowerscat displays it similar to how we display other properties.
> ![Screen Shot 2020-10-02 at 3 05 04 PM](https://user-images.githubusercontent.com/932566/94965266-ccbb7000-04c0-11eb-990e-227dde6c1ecf.png)
> 
> I'm wondering if we should try to be consistent with the way we display it in other places
> ![Screen Shot 2020-10-02 at 3 06 41 PM](https://user-images.githubusercontent.com/932566/94965345-ec529880-04c0-11eb-8fbc-3924e69fadb5.png)

@glassblowerscat @CarsonF 
Yes, I think making look like the screen shot above is a good idea, only can you unstack it? Also, I'm not sure if under the breadcrumb or under "Field Budget" would be better....Could I see what it looks like both ways?

**Comment by CarsonF** [comment]
I don't think it should be under Field Budget title. It's info about "Mine" - the project, not about the Field Budget.

**Comment by AmyRickwartz** [comment]
@glassblowerscat @CarsonF Can we do the visual like this?
<img width="371" alt="Screen Shot 2020-10-28 at 1 32 55 PM" src="https://user-images.githubusercontent.com/66033801/97481090-4dd02080-1922-11eb-8ec0-104b440f6532.png">

**Comment by sethmcknight** [comment]
@CarsonF is there anything outstanding on this one?
