### ISSUE TITLE
Add 'Budget History' and 'Updated' Date to Budget Card

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#474]
Update the Budget Card to include the 'Budget History' link and 'Updated' date per designs.
<img width="386" alt="Screen Shot 2020-09-18 at 2 13 52 PM" src="https://user-images.githubusercontent.com/7377802/93636580-ca81ed80-f9b9-11ea-9f17-27eae8f001e4.png">

**Comment by CarsonF** [comment]
Fixed with #492
