### ISSUE TITLE
Match Budget Card Loading State to Other Project Cards

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#475]
<img width="1552" alt="Screen Shot 2020-09-18 at 2 20 01 PM" src="https://user-images.githubusercontent.com/7377802/93637017-804d3c00-f9ba-11ea-8c14-cb5e5f515c05.png">
The Budget Card's loading state does not match the other cards.

The Budget icon is not included and both the Card Title and Data do not have a loading state.

**Comment by glassblowerscat** [comment]
Duplicate of #466
