### ISSUE TITLE
Remove/Delete Engagement

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#480]
Add an option to the Engagement Scene to Remove/Delete the Engagement.

This should only be available when the Project/Engagement is In Development.

**Comment by CarsonF** [comment]
Would be nice if this was backed by a `canDelete` field from our API. I'll raise this in Slack.

**Comment by glassblowerscat** [comment]
@CarsonF Where did we land on adding the `canDelete` field before doing this? I saw you and Michael had a brief discussion on Slack, but it didn't seem like a decision was reached.

**Comment by elisabeth-sorrell** [comment]
Working in conjunction with https://github.com/SeedCompany/cord-api-v3/issues/1526

**Comment by elisabeth-sorrell** [comment]
@CarsonF the `deleteEngagement` mutation is working for both language and intern types and ready for a UI button.
@michaelmarshall FYI..

**Comment by CarsonF** [comment]
Yeah I think this was more so for the `canDelete` boolean property, so we know whether to show or hide the UI button.

**Comment by elisabeth-sorrell** [comment]
@CarsonF I've confirmed that we can get a `canDelete` engagement property on a project's readOne.
