### ISSUE TITLE
Add 'Updated' Date to Files Card

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#481]
![](https://user-images.githubusercontent.com/7377802/93639471-a7a60800-f9be-11ea-9f7d-c0d49b5f6793.png)
Update the Files card to include the 'View Files' link and 'Updated' date per designs.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466668273) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
The view files link was added back in #492 

We don't have the updated date there, but we really don't have that data from the API either. All we have is the project's modified date. We do duplicate this date on the budget card but I don't like that because it's not the budgets date either.
