### ISSUE TITLE
Languages > Population field cropped on language listing.

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#501]
**Describe the bug**
Languages > Population field cropped on language listing.

**Steps to Reproduce**
1. Login
2. Click on the languages menu and view the population field

**Expected Result**
Population field should be displayed properly

**Actual Result**
Population field cropped on language listing.
See screenshot -  
![image](https://user-images.githubusercontent.com/5212585/93851206-5606c180-fccd-11ea-9a24-5bdc2543d8bc.png)

cord-field# b1ebad03

**Comment by CarsonF** [comment]
FWIW languages will never be that long without spaces
