### ISSUE TITLE
Adding Partners directly into CORD Field

### ISSUE THREAD

**Issue by megbacino** [SeedCompany/cord-field#51]
There is no way for Finance to enter new partners into CORD Field, they have to have Ken do this.  There should be a way for users to enter new partners into CORD field directly without going through BI, since Ken is the only one who can do this there is a delay in processing and has him doing work not related to BI

**Comment by sethmcknight** [comment]
@megbacino we've added this functionality into v3 as part of the Sakura Migration. Closing this issue.
