### ISSUE TITLE
BUG | Products display incorrectly on Language Engagement Card

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#521]
Products on a Language Engagement Card appear to be displaying the Product's GraphQL id rather than the name of the Product.

If there are more than 2 they also appear to be getting cut off at the bottom of the card.

<img width="676" alt="Screen Shot 2020-09-29 at 8 57 21 AM" src="https://user-images.githubusercontent.com/7377802/94568497-29edc200-0232-11eb-898b-d17e28a14020.png">

**Comment by frankyma** [comment]
I'm guessing the name is the producible's name?  What if it's a Direct Scripture Product?

Also what should we do about the multiple products?  Brining in @AmyRickwartz

**Comment by CarsonF** [comment]
I'm pretty sure we talked about removing products on this card, no?

**Comment by AmyRickwartz** [comment]
Yes, it was decided not to include the products on this card. I am attaching a screen shot of the design.
<img width="442" alt="Screen Shot 2020-10-05 at 1 44 59 PM" src="https://user-images.githubusercontent.com/66033801/95119238-43e74300-0711-11eb-8b94-88a658e5911a.png">

**Comment by frankyma** [comment]
@AmyRickwartz I think the screenshot is for a language card, not a language engagement card?

**Comment by frankyma** [comment]
Also does this have contradictory info?  A Language Engagement has status, but a Language has a number of active projects (an engagement is part of 1 project).  Also what date is ESAD?

**Comment by CarsonF** [comment]
> Also does this have contradictory info? A Language Engagement has status, but a Language has a number of active projects (an engagement is part of 1 project).

Yes there was some confusion here on the owner of these properties

> ESAD

Estimated Submission (to Area Director)

**Comment by AmyRickwartz** [comment]
Ok, so i don't think we designed that card then...I'm not seeing something like that in the figma file. I need to talk to Seth.

**Comment by frankyma** [comment]
Marked blocked on design until we confirm Language Engagement Card design and how it's different from lang card

**Comment by AmyRickwartz** [comment]
Ok, I worked through the design of the Language Engagement card with Seth and this is what we came up with. You can find this in the figma file under design system as well.
<img width="625" alt="Screen Shot 2020-10-08 at 1 38 59 PM" src="https://user-images.githubusercontent.com/66033801/95508045-00424280-0978-11eb-8a32-0e9bc6b5cd75.png">

**Comment by frankyma** [comment]
Overall looks good, a couple points:

1. Language Engagements don't have their own names, so I'll assume you mean the Language Name
2. AFAIK we don't use the ROD shorthand anymore, we spell out Registry of Dialects Code everywhere else
3. For some reason we currently don't show the language engagement status on the detail page (we do on internship engagements).  Should we?  That'll be a different ticket

**Comment by glassblowerscat** [comment]
I believe this is closed by #568

**Comment by AmyRickwartz** [comment]
> 3. For some reason we currently don't show the language engagement status on the detail page (we do on internship engagements).  Should we?  That'll be a different ticket

@frankyma - I think it probably should have the active status on the detail page if it's on the card.
