### ISSUE TITLE
Design System | Type Hierarchy

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#525]

**Comment by AmyRickwartz** [comment]
Researched best practices for creating type hierarchy in product design. 
Developed size and line heights based on our use of the 8pt grid system.
Created Figma type styles for each font in our font stack.
Need to discuss changing type sizes/possibility of changing type sizes in code with @CarsonF.
Reviewed with Patrick_Rutherford@tsco.org.

**Comment by AmyRickwartz** [comment]
Discussed changing the font stack sizes with Carson and he is ok with that.
