### ISSUE TITLE
Split out Engagement List query

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#526]
Currently the project details takes longer to load when there's several engagements.

We want to _work around_ this, but loading engagement list separate from the other project details.

It should have a separate loading state.

**Comment by frankyma** [comment]
Separating out the bottom engagement cards section loading should be simple enough, but the population total is a calculation of its engagements.  What should we do about this?

https://github.com/SeedCompany/cord-field/blob/edabe9367a8a1e38b6b4eebcff633e5658c4c1f1/src/scenes/Projects/Overview/ProjectOverview.tsx#L109-L116

**Comment by CarsonF** [comment]
😞 

Yeah we could have that be loading with the engagements as well
