### ISSUE TITLE
Add 'Locations' to Language Details & Edit

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#532]

**Comment by glassblowerscat** [comment]
This appears to be blocked by the API. My `canRead` and `canCreate` permission for `Language.locations` are always `false`, even if I created the language and/or am `root`. @CarsonF or @michaelmarshall, can you confirm that this is unintended behavior that requires an API change?

**Comment by CarsonF** [comment]
Yes it's a permissions problem right now.

**Comment by glassblowerscat** [comment]
I've done a little work on this in branch `(https://github.com/SeedCompany/cord-field/tree/532-add-locations-to-language-details-and-edit)[https://github.com/SeedCompany/cord-field/tree/532-add-locations-to-language-details-and-edit]`, using hard-coded data, but we're also blocked on the "Edit" side of things by the fact that `UpdateLanguageInput` doesn't have a `locations` field.

**Comment by CarsonF** [comment]
Ok we need `addLocationToLanguage` and `removeLocationFromLanguage` mutations

**Comment by frankyma** [comment]
> Ok we need `addLocationToLanguage` and `removeLocationFromLanguage` mutations

@CarsonF do we need these separate mutations?  Or can we just expose a locationId field on update like we do on Project
