### ISSUE TITLE
[Design] Language Details View

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#536]

**Comment by ParkeBrown** [comment]
@sethmcknight can you add some requirements/description/required fields for this card?

**Comment by sethmcknight** [comment]
Name
Name Pronunciation

Public Name
Public Name Pronunciation

Ethnologue Name
Ethnologue Name Pronunciation

Ethnologue Code
Provisional Code

Dialect Tag
Dialect Number

Sign Language Tag
Sign Language Code

Least of These Tag
Least of These Reasoning

Sensitivity

Sponsor Begin Date
Estimated Sponsor End Fiscal Year

Locations

Projects

**Comment by ParkeBrown** [comment]
Amy going to talk to Carson and Patrick
