### ISSUE TITLE
Calculate "Total Interns" on Internship Projects

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#539]
On Internship Projects we should calculate and display the "Total Interns" in the project, similar to the "Population Total" we are displaying on Translation Projects.

Since each Intern Engagement is a single person, this field will total and display the number of Intern Engagements in the Internship Project.

**Comment by CarsonF** [comment]
That means we are showing this info in 2 spots.
![Screen Shot 2020-10-06 at 5 04 10 PM](https://user-images.githubusercontent.com/932566/95265060-0b6d6500-07f6-11eb-8a00-e8ffcdd14e6e.png)
