### ISSUE TITLE
[BUG] Searching by a term that has already been searched for only returns the cached search results.

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#546]
- Search for a term (ex. Oct)
- Load Search Results
- Create a new item that includes that term (ex. Oct 5th Project)
- Search for term again (ex. Oct)

Expected Results: Newly created item will be included in search results

Actual Results: Only the original results are returned.

**Comment by glassblowerscat** [comment]
We're treating this as a symptom of #547—what we need to do is use the `update` method of all "Create" mutations to feed the returned new item into the cache
