### ISSUE TITLE
[BUG] Duplicate Data Button for 'Estimated Submission' Date

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#548]
There are two data buttons displaying for the 'Estimated Submission' date on the Project Details scene. Editing either one edits both. There should only be one input and display for this.

<img width="808" alt="Screen Shot 2020-10-05 at 2 44 36 PM" src="https://user-images.githubusercontent.com/7377802/95124820-9fb5ca00-0719-11eb-81e9-127e0c6284bd.png">

**Comment by frankyma** [comment]
I'm having trouble reproducing this and looking at the code it's I can't see how it's rendering two buttons.

@sethmcknight Is this in all your projects?  Old and new?  Intern or Language?

**Comment by sethmcknight** [comment]
@frankyma I just checked again now that all the issues getting back in have been resolved. I'm not seeing this anymore. Must have been a weird issue with the original deployment. I'll close this out.
