### ISSUE TITLE
Project Files | Visually represent that more than one version exists

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#555]
As a user, I would like to know when looking at a file that multiple versions exist so that I can know if I should look at the history of the file.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466679748) by [Unito](https://www.unito.io)

**Comment by frankyma** [comment]
@sethmcknight @AmyRickwartz any design specs on how you want this done?

**Comment by AmyRickwartz** [comment]
> @sethmcknight @AmyRickwartz any design specs on how you want this done?

Hi @frankyma ! I'm working on the design for this in the next sprint. It's not designed yet. Thanks!
