### ISSUE TITLE
Redacted engagement total width

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#559]
![Screen Shot 2020-10-06 at 4 38 26 PM](https://user-images.githubusercontent.com/932566/95262790-6d2bd000-07f2-11eb-915e-1440a842970c.png)

The fact that the API says we can't read it but then gives us a filled list is another problem..

**Comment by frankyma** [comment]
The width is a simple fix, but 
> The fact that the API says we can't read it but then gives us a filled list is another problem..
This is a more pressing issue.  @CarsonF I can't reproduce this are you seeing this with latest master and new data?

**Comment by CarsonF** [comment]
My data is probably old then
