### ISSUE TITLE
Language Engagement Detail Style Bugs

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#560]
![Screen Shot 2020-10-06 at 4 40 37 PM](https://user-images.githubusercontent.com/932566/95262958-b54af280-07f2-11eb-8f23-65999826d09c.png)

- [ ] Width should be limited to normal value.
- [ ] "Products" title is too close to bottom of dedication card too

**Comment by CarsonF** [comment]
Err never mind this is just a regression with #427 

/cc @glassblowerscat

**Comment by glassblowerscat** [comment]
> Err never mind this is just a regression with #427
> 
> /cc @glassblowerscat

Blarg

**Comment by frankyma** [comment]
Seems fixed 👍

**Comment by glassblowerscat** [comment]
> Seems fixed 👍

Yup, fixed in #427
