### ISSUE TITLE
Projects > Project listing view is blinked when refreshing the page

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#562]
**Describe the bug**
Projects > Project listing view is blinked when refreshing the page

**Steps to Reproduce**
1. Login
2. Click on the Projects menu and sort project Z-A

**Expected Result**
Project listing view should not be blinked If no projects are created.

**Actual Result**
Project listing view is blinked when refreshing the page. (Pause the video at 0:11 seconds and view the result )
See video-  https://drive.google.com/file/d/1DQjUp59kMnAZCng5pZOq40wZmuls9naF/view?usp=drivesdk

**Note:** 
I can replicate the same issue in Language, Partner, and People listing.

cord-field# 74f83c10

**Comment by CarsonF** [comment]
This is working as intended. We are showing a loading state while we request data from the API. A hosted environment with actual data is much slower.
