### ISSUE TITLE
createPartner > Getting "user QxKiKQ3S1 does not have the requested power: CreateOrganization" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#577]
**Describe the bug**
createPartner > Getting `user QxKiKQ3S1 does not have the requested power: CreateOrganization` error

**Steps to Reproduce**

1. Clear the DB
1. Login
1. Click on `Create New Item Button > Partner > Add Organization`
1. Click on `Submit` button

**Expected Result**
Partner should be created from UI without calling `grantPower` API manually.

**Actual Result**
Getting `user QxKiKQ3S1 does not have the requested power: CreateOrganization` error 
See video -  https://drive.google.com/file/d/1kvxz8PazPZb4Ru8RqlF4JjofUk5l45tm/view?usp=drivesdk

**Note:** I can replicate the same issue in Person and Language.

cord-field# fdc26451

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466685052) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
Related to #578
