### ISSUE TITLE
[Design] Always Visible Labels on Data Buttons

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#588]
> Users have noted that it can be difficult to know what a data button is for once it has data. They have asked if we would consider adding labels that are always visible.
> -- Seth

**Comment by CarsonF** [comment]
Maybe this means we are using those buttons too much. @AmyRickwartz @prutherford what do yall think?

**Comment by AmyRickwartz** [comment]
I have come up with three options for this. You can also inspect these in the figma file under PROJECTS > Project Detail View.

Option A
<img width="407" alt="Screen Shot 2020-10-30 at 1 03 14 PM" src="https://user-images.githubusercontent.com/66033801/97741396-a7665580-1ab0-11eb-97e2-93e886604e9c.png">

Option B
<img width="399" alt="Screen Shot 2020-10-30 at 1 03 23 PM" src="https://user-images.githubusercontent.com/66033801/97741420-b0572700-1ab0-11eb-937c-1db848aa6a7a.png">

Option C
<img width="410" alt="Screen Shot 2020-10-30 at 1 03 33 PM" src="https://user-images.githubusercontent.com/66033801/97741446-ba792580-1ab0-11eb-955c-ecdadc7c3d81.png">

@CarsonF What do you think? @sethmcknight Would it be a good idea to run these past the people who where commenting about this issue when beta testing? 

I think the distinction between label and information is more clear on Options 1 & 3. Option 2 seems like and easy fix, but I don't know if its as easily readable as the other two...but it does work.

**Comment by sethmcknight** [comment]
@AmyRickwartz I personally like Option 2, but yes we should probably run these past some of the beta testers. 

@CarsonF Do you have any thoughts on which of these would be best?

**Comment by CarsonF** [comment]
The labels on 2 seem to be the most consistent with our other labels in the app.
Something else to think about though is if the field is unreadable then we "gray out" the entire button. So this would also hide the label on 2 and 3. Having a hard time getting a screenshot for yall, but it's just like the loading boxes without the pulse effect.

**Comment by ParkeBrown** [comment]
Seth ok with taking recommendation and moving forward.

**Comment by ParkeBrown** [comment]
Going with option 2

**Comment by AmyRickwartz** [comment]
Ok, I just talked with Patrick and he is thinking Option C actually looks the most UX-y and easy to read and also looks like our log in boxes. **So let's go with option C**. I'll clean up the figma file tomorrow so you can look at it @CarsonF .
