### ISSUE TITLE
Language > Language name is missing on the listing and language details page

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#595]
**Describe the bug**
Language > Language name is missing on the listing and language details page

**Steps to Reproduce**

1. Login
1. Click on ` Language menu > Select Language`
1. Again click on a languages menu

**Expected Result**
The language name should be displayed on the listing and language details page.

**Actual Result**
Language name is missing on the listing and language details page.
See video -  https://drive.google.com/file/d/1Tc6IG-rdExiU8lcefvWm18lLC6aDh9-o/view?usp=sharing

cord-field# 756f703b

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466691377) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
Looks like a permission issue. In other places we show a "redacted" gray box. Not sure about the data on the list cards though. I also thought language name was public.
