### ISSUE TITLE
Create Selenium UI Workflow Tests

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#597]
Piyush, it would help the team to have these based on this sheet that Seth will give you access to here: https://docs.google.com/spreadsheets/d/1MxpNMTEkhSYptWsJxTy9RdF9kipxYm2jDFzAP-8GhdY/edit#gid=1413317393

**Comment by iPiyushPatel** [comment]
Sure thing @ParkeBrown. I'll start working on it and keep you posted with progress. Thanks.

**Comment by ParkeBrown** [comment]
@iPiyushPatel no rush but sometime next week could you call out where you're tracking this?
