### ISSUE TITLE
Cancelling an edit while loading causes a crash

### ISSUE THREAD

**Issue by frankyma** [SeedCompany/cord-field#598]
STR: Open Project or partner details, edit something, when edit is submitted and loading (may have to put a delay in the api or interrupt the browser call) click close.

ER: close button disabled on loading
AR: click close and hard crash

@CarsonF I think the best solution is to disable the close button while loading.  If we have it enabled the user will expect clicking close will revert the edit, which is a much bigger task.  Thoughts?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43487134/96643885-0e2f8600-12dd-11eb-98fa-b8591d78e608.gif)

**Comment by CarsonF** [comment]
I thought I opened an issue for this, but I can't find it now. Yeah I think disabling the close button is the easiest solution.
