### ISSUE TITLE
[BUG] Can't set the Financial Reporting Type of a Partnership

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#606]
After successfully creating a Managing Partnership without a Financial Reporting type, I go back and attempt to edit the Partnership to add the Financial Reporting Type.

After selecting the type and saving, the system times out. The Financial Reporting Type is never added.

**Comment by frankyma** [comment]
same issue as https://github.com/SeedCompany/cord-api-v3/issues/1409
