### ISSUE TITLE
[BUG] Search returns Organization rather than Partner

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#607]
When creating a new Partner, one is required to create a new Organization as well. Once the Partner is created with the same name as the Organization, searching for the Name returns the Organization in the search results rather than the partner. 

This can be seen when selecting the card in the search results. A blank details page is shown (No Name displayed and nothing indicating it is an organization). However checking the URL shows it is looking at /organizations/id rather than /partners/id.

If you are able to find the new Partner in the Partners list and select it, it will correctly take you to the /partners/id detail page.

**Comment by CarsonF** [comment]
We need to specify `types` on the search to blacklist organization reuslts
