### ISSUE TITLE
[BUG] Department ID Could Not be Set

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#630]
When submitting a Project with a valid Primary Location for Finance Confirmation, I received an error that the Department ID could not be set.

We need to ensure that:

1) A project with a valid Primary Location assigned always receives a valid Department ID when submitted for Finance Confirmation.
2) A project without a valid Primary Location cannot be submitted for Finance Confirmation.
3) The Department ID is displayed when set.

**Comment by CarsonF** [comment]
The problem is the `fundingAccount` on `Location` is optional. So since that is missing the department ID cannot be calculated. Not sure the best process going forward. Only allow locations to be assigned to the `Project.primaryLocation` if they have a funding account?

**Comment by sethmcknight** [comment]
@CarsonF yes I think that makes sense. Have we not migrated the funding accounts with Locations?

**Comment by CarsonF** [comment]
> Have we not migrated the funding accounts with Locations?

Question for @michaelmarshall @blakekrammes

**Comment by blakekrammes** [comment]
Yes.

**Comment by frankyma** [comment]
Duplicate of https://github.com/SeedCompany/cord-api-v3/issues/1499
