### ISSUE TITLE
[BUG] Financial Reporting Type could not be assigned to this partnership

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#631]
When attempting to add any Financial Reporting Type to any Managing Partnership users receive the error 'FinancialReportingType "Type" cannot be assigned to this partnership'

We need to ensure the following:

1) Managing Partners should have at least 1 valid Financial Reporting Type
2) The valid Financial Reporting Types should be able to be selected for a Managing Partner

**Comment by frankyma** [comment]
This is probably because you were assigning a financial reporting types to a non-managing partner, which was allowed because the FE didn't check the types available on the partner.  Should be fixed by: https://github.com/SeedCompany/cord-field/pull/627
