### ISSUE TITLE
[BUG] Upload Manager blocks users from interacting with the search box

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#635]
Expected Results
Upload a file
The upload manager opens
Click on the search box
The search box is selected

Actual Results:
Upload a file
The upload manager opens
Click on the search box
The search box is not selectable
Close upload manager
Click on the search box
The search box is selected.

**Comment by CarsonF** [comment]
Still trying to figure out why. I did discover that the same thing happens with budget record edit fields.

**Comment by ParkeBrown** [comment]
See #732 for testing documentation
