### ISSUE TITLE
[BUG] Partner List Sort does not work

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#636]
The partner list is not sorting alphabetically by the Partner Name.

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown changes have been merged in

**Comment by ParkeBrown** [comment]
@iPiyushPatel would you test to confirm bug is resolved?

**Comment by iPiyushPatel** [comment]
@ParkeBrown 
I've checked on the latest master c8436f62 and it's working fine.
