### ISSUE TITLE
Add Files Count to Files Card

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#638]
![](https://user-images.githubusercontent.com/7377802/93639471-a7a60800-f9be-11ea-9f7d-c0d49b5f6793.png)

Add the total count of a Project's files to the Files card

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466703048) by [Unito](https://www.unito.io)

**Comment by glassblowerscat** [comment]
This is blocked by the API. The `total` property for `project.rootDirectory.value.children` only reflects the total number of items in that top-level directory; items in sub-folders are not counted.
