### ISSUE TITLE
[BUG] Could Not Change Step error

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#643]
When changing the project step received the following error. On refresh, the step had been changed.

'''"errors":[{"message":"Could not update step changed at on project","extensions":{"codes":["Server"],"status":500,"code":"Server","exception":{"message":"Could not update step changed at on project","stacktrace":["at ProjectStepChangedAtHandler.handle (components/project/handlers/set-step-changed-at.handler.ts:45:13)"]}},"locations":[{"line":2,"column":3}],"path":["updateProject"]}],"data":null,"extensions":{"tracing":{"version":1,"startTime":"2020-10-29T12:47:43.806Z","endTime":"2020-10-29T12:47:47.810Z","duration":4003985033,"execution":{"resolvers":[{"path":["updateProject"],"parentType":"Mutation","fieldName":"updateProject","returnType":"UpdateProjectOutput!","startOffset":394327,"duration":4002953117}]}}}}'''

**Comment by frankyma** [comment]
Cannot repo locally, may be data issue or more specific STR
