### ISSUE TITLE
[BUG] Error adding data to project

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#644]
Received error 'Could not find object' multiple times when trying to add data to a project via the data buttons.

'''{"errors":[{"message":"Could not find object","extensions":{"codes":["Input","Client"],"status":400,"code":"Input","exception":{"message":"Could not find object","stacktrace":["at DatabaseService.sgUpdateProperty (core/database/database.service.ts:206:13)","at DatabaseService.sgUpdateProperties (core/database/database.service.ts:130:17)","at ProjectService.update (components/project/project.service.ts:614:20)","at ProjectResolver.updateProject (components/project/project.resolver.ts:264:21)"]}},"locations":[{"line":2,"column":3}],"path":["updateProject"]}],"data":null,"extensions":{"tracing":{"version":1,"startTime":"2020-10-29T12:50:03.403Z","endTime":"2020-10-29T12:50:04.689Z","duration":1285166996,"execution":{"resolvers":[{"path":["updateProject"],"parentType":"Mutation","fieldName":"updateProject","returnType":"UpdateProjectOutput!","startOffset":582617,"duration":1282908861}]}}}}'''

**Comment by frankyma** [comment]
Cannot repo locally, may be data issue or more specific STR

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on the latest develop e8bb4ac and can't reproduce this issue.
See video :

https://user-images.githubusercontent.com/5212585/134858390-34175024-9a21-482c-92bb-ba9441971183.mp4
