### ISSUE TITLE
Design System | Colors

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#669]
Design system work planned by Amy and Patrick

**Comment by AmyRickwartz** [comment]
- Discussed use of alpha channel vs RGB numbers for gray type. Carson prefers alpha channel https://material.io/design/color/text-legibility.html#legibility-standards .
- Creating Figma color styles for type — black and white — for varying emphasis: high, medium, disabled.
- Produced primary and secondary colors guide with the gradations and hex numbers—included Figma color styles.
- Produced other colors in color palette with color guide.
