### ISSUE TITLE
Products - Methodology Options

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#677]
When users select a `Methodology`, we need to save the corresponding `Approach` as well.

Additionally we need to add some options for `Methodology`. The available options should match what is listed below. When a `Methodology` of `Other` is selected, the user should receive a description field to explain what the new `Methodology` is.

Written Approach

- Paratext

- Other Written [add a description field]

Oral Translation Approach

- Render

- Audacity

- Adobe Audition

- Other Oral Translation [add a description field]

Oral Stories Approach

- Story Together

- Seed Company Method

- One Story

- Craft 2 Tell

- Other Oral Stories [add a description field]

Visual Approach

- Film

- Sign Language

- Other Visual [add a description field]

**Comment by ParkeBrown** [comment]
@sethmcknight I believe this was a desired launch item that will now become a feature to develop. Is that true?

**Comment by sethmcknight** [comment]
This looks correct in v3, should be considered done
