### ISSUE TITLE
BUG | Products Duplicating

### ISSUE THREAD

**Issue by njross33** [SeedCompany/cord-field#68]
When a user is on a project and then they go to Plan, then Products, if you go to add a product and fill in the necessary info (type, purposes, methodology, etc) it duplicates. I've seen this on two different tickets today with projects and the only similarity is that they both used Paratext as the methodology. I had to go into Mongo and delete one and manually enter in the data into Mongo for it to stick.

**Comment by sethmcknight** [comment]
When a user attempts to update a Product on a Language Engagement, a duplicate is created and the updated information is not saved. It appears this is due to Products not having ID's. We need to resolve this issue so that users are able to keep their Products correct.

**Comment by sethmcknight** [comment]
Team Estimated at 13 storypoints.

**Comment by blakekrammes** [comment]
@njross33, @sethmcknight,

Do you have an example of a project or projects that have this bug? I haven't been able to reproduce it yet.
