### ISSUE TITLE
Project > Getting "Post-upload action failed" error while adding deleted file again

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#687]
**Roles:** All

**Describe the bug**
Project > Getting `Post-upload action failed` error while adding deleted file again

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and go to the created project's listing page
3. Open project created by Admin
4. Click on the `upload file` button and add two files having the same name
5. Click on the `View Files` button
6. Delete the uploaded file
7. Upload the same file which is deleted

**Expected Result**
User should be allowed to upload the deleted file.

**Actual Result**
Getting `Post-upload action failed` error while adding deleted file again.
See video - https://drive.google.com/file/d/1n9cGo-GC0eOLIAyBv0qLnxMni40Pazri/view?usp=drivesdk

cord-field# c8436f62

**Comment by CarsonF** [comment]
FYI Video is private

**Comment by iPiyushPatel** [comment]
Done @CarsonF - video is public now.

**Comment by sethmcknight** [comment]
Closing this out, we haven't seen this since launch. If it comes up again we can reopen.
