### ISSUE TITLE
Project > Files > Getting "Unhandled Rejection (Invariant Violation): cache-only fetchPolicy option should not be used together with query refetch." error while deleting the main version of the file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#689]
**Roles:** All

**Describe the bug**
Project > Files > Getting `Unhandled Rejection (Invariant Violation): cache-only fetchPolicy option should not be used together with query refetch.` error while deleting the main version of the file

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and go to the created project's listing page
3. Open project created by Admin
4. Click on the `view files` button
5. Upload a new file e.g. test1
6. Click on the file `kebab menu` and add the file new version e.g.test2
7. Close the file `Upload Manager` menu
8. Again click on the `kebab menu` and click on the `history` button
9. Delete the main version of the file i.e. test1 and wait

**Expected Result**
The event should be performed without an error.

**Actual Result**
Getting `Unhandled Rejection (Invariant Violation): cache-only fetchPolicy option should not be used together with query refetch.` error while deleting the main version of the file.
See video - https://drive.google.com/file/d/1U6CryIpEFtu-RqDyY5aljQMKC53itena/view?usp=drivesdk

cord-field# 89ee57a1

**Comment by sethmcknight** [comment]
Closing this out, we haven't seen this since launch. If it comes up again we can reopen.
