### ISSUE TITLE
Project > Files > Getting "Not Found" error while re deleting file which is already deleted

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#690]
**Roles:** All

**Describe the bug**
Project > Files > Getting `Not Found` error while re deleting file which is already deleted

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and go to the created project's listing page
3. Open project created by Admin
4. Click on the `view files` button
5. Upload a new file e.g. test1
6. Click on the file `kebab menu` and click on the `History` button
7. Delete the i.e. test1 file 
8. Again delete the same file

**Expected Result**
Proper validation message should be displayed

**Actual Result**
Getting `Not Found` error while re deleting file which is already deleted.
See video - https://drive.google.com/file/d/14Fbs7GXvsHfAhWFe654A7Vhy1TREuQ24/view?usp=drivesdk

cord-field# 89ee57a1
cord-api-v3# a99ebf10

**Comment by sethmcknight** [comment]
Closing this out, we haven't seen this since launch. If it comes up again we can reopen.
