### ISSUE TITLE
Project > Files > Getting "Could not get file download URL" error while clicking on the file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#691]
**Roles:** All

**Describe the bug**
Project > Files > Getting `Could not get file download URL` error while clicking on the file

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and go to the created project's listing page
3. Open project created by Admin
4. Click on the `view files` button
5. Upload a new file e.g. test1
6. Click on the file `kebab menu` and click on the `History` button
7. Delete the i.e. test1
8. On the file listing page click on the file i.e. test1

**Expected Result**
Better validation message should be displayed OR
should not be allowed to delete the default file version OR
the file should be deleted without an error.

**Actual Result**
Getting `Could not get file download URL` error while clicking on the file
See video - https://drive.google.com/file/d/1cExUr56pe8w2ONVts5D4KfkfBQluOEnu/view?usp=drivesdk

cord-field# 89ee57a1
cord-api-v3# a99ebf10

**Comment by sethmcknight** [comment]
Closing this out, we haven't seen this since launch. If it comes up again we can reopen.

**Comment by iPiyushPatel** [comment]
Hi @sethmcknight 
I've verified on latest develop b7880e70 and still replicate the issue, Attaching the video for reference. Reopening the task. Thanks!
See video : 

https://user-images.githubusercontent.com/5212585/114141351-1c2a9f00-992f-11eb-8912-af3b00ad3a2f.mp4
