### ISSUE TITLE
Project > Team members > Role Dropdown is not closed automatically after adding the user role

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#695]
**Roles:** All

**Describe the bug**
Project > Team members > Role Dropdown is not closed automatically after adding the user role

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and assigned team member `consultant`
3. Open Project created by an admin user
4. Open the team member list and click on the `Add Team Member` button
5. Add Person name role

**Expected Result**
Role Dropdown should be closed automatically after adding the user role

**Actual Result**
Role Dropdown is not closed automatically after adding the user role
See video - https://drive.google.com/file/d/1LpWa6qCidqkToWnaQTSvkRwZ8krRhaUC/view?usp=drivesdk

cord-field# 89ee57a1

**Comment by CarsonF** [comment]
That's because multiple roles can be selected. You can just click anywhere off of the dropdown or hit esc to close it

**Comment by ParkeBrown** [comment]
@sethmcknight this feels like something you could either put on a future change list or close. It sounds like close might be the answer.

**Comment by sethmcknight** [comment]
Yes, this works as it should. Closing.
