### ISSUE TITLE
Project > File > User can upload files having duplicate names multiple times

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#696]
**Roles:** All

**Describe the bug**
Project > File > User can upload files having duplicate names multiple times

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project 
3. Click on the `View file` button
4. Click on the `Upload file` button 
5. Add file1 
6. Again Add file1

**Expected Result**
The duplicate file name should not be allowed

**Actual Result**
User can upload files having duplicate names multiple times.
See video - https://drive.google.com/file/d/1CqFa7rKZpiqb-GRU72c5YToz5KOf9icM/view?usp=drivesdk

cord-field# 89ee57a1

**Comment by CarsonF** [comment]
We treat that as a new version of the same file. You can see that in the file's "history".

**Comment by ParkeBrown** [comment]
@sethmcknight can we close this?
