### ISSUE TITLE
Project > Language Engagement > Product > Consultant can not edited created product details

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#699]
**Roles:** Consultant

**Describe the bug**
Project > Language Engagement > Product >  Consultant can not edited created product details

**Steps to Reproduce**
1. Login as Admin user
2. Create a new project and assigned team member `consultant`
3. Add Language engagement
4. Click on created `Language engagement`
5. Add a product in the created `Language engagement` and click on the `Save` button
6. Login as consultant user
7. Open Project created by an admin user
8. Click on the created `Language engagement`
9. Open added Product and click on the `save` button

**Expected Result**
Consultant Should be edited created product details

**Actual Result**
Consultant can not edited created product details
See video - https://drive.google.com/file/d/1aLe28hx3xvW2eDlpHU_0FJRhSks1Au-U/view?usp=drivesdk

cord-field# 89ee57a1

**Comment by daniel-leod** [comment]
Consultant role does not have permissions to edit products.
