### ISSUE TITLE
Update Internship Position

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#70]
The Internships Program has made changes to the Roles/Types of internships we track. We need to update these existing options and map current internships to their new version.

See files here: 

https://drive.google.com/open?id=1e9KZBcy6lqrBnOWQ0s6ywd6Kg-31HZkq

https://drive.google.com/open?id=18iK6br_O5hlt76D3FX6f8qGRmDDh09sK

**Comment by CarsonF** [comment]
@sethmcknight What about _Linguistic Consultant_? I don't see it on the existing or updated titles.

**Comment by sethmcknight** [comment]
@CarsonF waiting on a response from the Internship program manager

**Comment by sethmcknight** [comment]
@CarsonF it looks like that isn't currently associated with any Intern Engagements. Let's just drop it for now.
