### ISSUE TITLE
Forgot Password > "You have submitted a password change request" and "Check your Email" both page gets open when user click on "Reset Password" button

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#702]
**Roles:** All

**Describe the bug**
Forgot Password > `You have submitted a password change request` and `Check your Email` both page gets open when user click on `Reset Password` button

**Steps to Reproduce**
1. Click on the `Forgot password link` on the login page
2. Enter email id
3. Click on the `Reset Password` button

**Expected Result**
`You have submitted a password change request` or `Check your Email` any one page should be open

**Actual Result**
`You have submitted a password change request` and `Check your Email` both page gets open
See video - https://drive.google.com/file/d/1CIx_7gsiU3pc6dGkkcjaOrXGRffXQlsb/view?usp=drivesdk

**Note:** Forgot password Email is not received in the entered email box

CordAPIV3# 89ee57a1

**Comment by CarsonF** [comment]
That's a convince option in the API for development. Emails open in browser instead of being sent. There's also no way to send the email in development without AWS SES credentials since we talk to that API directly to do the sending instead of a local SMTP service.
