### ISSUE TITLE
Edit person> "Edit icon" shrinks when the user add "> 55" character in the person "firstName" and "lastName" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#704]
**Roles**: All

Describe the bug
Edit person> `Edit icon` shrinks when the user add `> 55` character in the person `firstName` and `lastName` field

**Steps to Reproduce**
1. Login with admin user
2. Create a new Person and Click on that Person to open the details page
3. Click on the person  `Edit Icon` and add `> 55` character into the person `firstName` and `lastName` field
4. Click on the `Save` button

**Expected Result**
`Edit Icon` should be displayed without shrinks.

**Actual Result**
`Edit icon` shrinks when the user add `> 55` character in the person `firstName` and `lastName` field
See video - https://drive.google.com/file/d/1c6nGhDabo8u48xqpRWUTAX_q7tUv6bff/view?usp=drivesdk

**Note:** Ican replicate the same issue for Project name

CordAPIV3# 89ee57a1

**Comment by CarsonF** [comment]
![Screen Shot 2021-03-01 at 9 13 39 AM](https://user-images.githubusercontent.com/932566/109517013-73a33880-7a6e-11eb-91d2-0561eaae840a.png)

Does it deform if you have spaces in the name?

**Comment by ParkeBrown** [comment]
It appears to:
https://cordfield.com/users/5c3d88847219425288a3cb59
![Screen Shot 2021-03-01 at 10 56 44 AM](https://user-images.githubusercontent.com/5691814/109523039-e9160580-7a7c-11eb-97e8-f5df9c0344a3.png)

**Comment by ParkeBrown** [comment]
And partially when using something smaller
https://cordfield.com/users/5c3d88847219425288a3cb59
![Screen Shot 2021-03-01 at 10 59 20 AM](https://user-images.githubusercontent.com/5691814/109523331-3eeaad80-7a7d-11eb-8faa-e42f029c40c2.png)
