### ISSUE TITLE
Login > Getting  "Something wasn't right. Try again, or reset password." error when a user enters valid credentials

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#710]
**Roles:** All

**Describe the bug**
Login > Getting  `Something wasn't right. Try again, or reset password.` error when a user enters valid credentials

**Steps to Reproduce**
1. docker-compose down
2. docker-compose pull db
3. docker-compose up -d db
4. yarn
5. yarn start: dev
6. Login as a root user

**Expected Result**
The user should be logged in.

**Actual Result**
Getting  `Something wasn't right. Try again, or reset password.` error when a user enters valid credentials
See video - https://drive.google.com/file/d/1NbgF3-CzdP4mwwhCdkOBujnHlDS0IgXz/view?usp=drivesdk

**Note:**:  Two root-id is generated in output when hit `yarn start: dev` command.

cord-field# daaa908f
cord-api-v3# d5f848cb

**Comment by ParkeBrown** [comment]
Logs when I attempted
![image](https://user-images.githubusercontent.com/5691814/105764701-4d492500-5f25-11eb-8a93-d8ac05166913.png)

**Comment by michaelmarshall** [comment]
So far I'm seeing this only happen on a db that has no data/constraints/indexes. When restarting an API server on a DB that has had an API bootstrap it, I don't see this behavior.

**Comment by michaelmarshall** [comment]
commit 8ab5e1107c351c111560d379c8cbe54f50dfcf09 does not have this bug. commit d5f848cbe80961aac59856c7a460d1ee6c7f653d does.
![image](https://user-images.githubusercontent.com/1165460/105778077-37416180-5f31-11eb-851e-b8b7f3e291b5.png)

**Comment by CarsonF** [comment]
Would @iPiyushPatel @ParkeBrown try this again after pulling the latest API code? The root user password should always match what yall have configured in your env (`.env.local` file).

**Comment by ParkeBrown** [comment]
Attempted to do so, even using both pw just in case. No luck. Could be user error but I have limited time to troubleshoot today.

**Comment by ParkeBrown** [comment]
@CarsonF Piyush still confirms this is an issue for him. Save for a few calls, I'm generally open to test

**Comment by iPiyushPatel** [comment]
Hi, @michaelmarshall @ParkeBrown 
I've verified the latest develop 9fa4b368 and it's working fine.
