### ISSUE TITLE
test movie embed

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-field#711]
https://user-images.githubusercontent.com/1165460/106022769-cf535e00-608b-11eb-9361-546473a43a71.mov

**Comment by michaelmarshall** [comment]
I just dragged a file from my file system into the input box.

**Comment by ParkeBrown** [comment]
The files we're discussing are larger than the file size limit and not in an allowed format. I'll talk through options. Thanks for this.
