### ISSUE TITLE
Project Favorites/Subscriptions Design

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#718]
- [x] Define 
- [x] Design 
- [x] Review
- [x] Prototype
- [ ] Test
- [ ] Analyze & Report
- [ ] Review 
- [ ] Design Adjustments (if necessary)

- Allow users who are not part of the Project Team to Favorite/Subscribe to a Project
- This Project would then show up in their ‘My Projects’ list
- Especially useful for EDR’s, Communications, etc
- Would be good to denote on the Project card if it is a Favorite/Subscription

**Comment by sethmcknight** [comment]
I need to get a list of users to test with. We should go ahead and set up those testing sessions this sprint.

We should plan to have designs done by the end of this sprint. We'll then test and refine next sprint.

**Comment by sethmcknight** [comment]
@AmyRickwartz here's some users you could reach out to for testing:

Advancement
- Becca Lewis
- Annie Jones
- Jessica Lambaise
- Amy Reynolds
- Dana Fay
- Tony Pitaniello
- Scottye Perry
- Sweena Varghese

Communications
- Paula Kordic
- Kim Driggers
- Lauren Kidd

**Comment by ParkeBrown** [comment]
Blocker on getting prototype to work; Amy going to reach out to Patrick

**Comment by AmyRickwartz** [comment]
> Blocker on getting prototype to work; Amy going to reach out to Patrick

Got it figured out. Working on the prototypes again.

**Comment by AmyRickwartz** [comment]
Defining | Designing | Review | Testing | Anylyize Results | Housekeeping | Complete
-- | -- | -- | -- | -- | -- | --


 

Define

 Design

 Review

 Prototype

 Test

 Analyze & Report

 Review

 Design Adjustments (if necessary)

Allow users who are not part of the Project Team to Favorite/Subscribe to a Project

This Project would then show up in their ‘My Projects’ list

Especially useful for EDR’s, Communications, etc

Would be good to denote on the Project card if it is a Favorite/Subscription

**Comment by AmyRickwartz** [comment]
`
<a href="https://www.figma.com/proto/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=4312%3A31014&amp;scaling=min-zoom">

<span style="font-size:13pt;background-color:#F8F8F8;font-family:Arial,sans-serif;">
Prototype 2</span></a></span>
<br>
<b><span style="color:#1D1C1D;font-size:11.5pt;font-family:Arial,sans-serif;">
“Pinning” Translation Project - Details View</span></b>
<br>
<i><span style="color:#1D1C1D;font-size:11.5pt;font-family:Arial,sans-serif;">
This link will keep updating as I rework the design and finish out all the connections…so you can check back on it. It currently still looks like the first design.</span></i>`

**Comment by AmyRickwartz** [comment]
### LINKS TO PROTOTYPES:

<a href="https://www.figma.com/proto/IfEmcJeuNY6ucgjYctlKB7/Cord-Field---Current?node-id=4417%3A4224&scaling=min-zoom" target="_blank" rel="noreferrer noopener"> 
<span style="font-size:13pt;background-color:#F8F8F8;font-family:Arial,sans-serif;">
Prototype 1.3</a></span>
<br> 
<b><span style="color:#1D1C1D;font-size:11.5pt;font-family:Arial,sans-serif;"> 
“Pinning” Translation Project - List View</span></b> 
<br> 
<i><span style="color:#1D1C1D;font-size:11.5pt;font-family:Arial,sans-serif;"> 
This link will keep updating as I finish out all the connections…so you can check back on it.</span></i>
<br>
<br>

<span style="font-size:13pt;background-color:#F8F8F8;font-family:Arial,sans-serif;"> 
<a href="https://www.figma.com/proto/IfEmcJeuNY6ucgjYctlKB7/Cord-Field?node-id=4312%3A30523&scaling=min-zoom" target="_blank" rel="noreferrer noopener"> 
Prototype 2</a></span>
<br> 
<b><span style="color:#1D1C1D;font-size:11.5pt;font-family:Arial,sans-serif;"> 
“Pinning” Translation Project - Details View</span></b> 
<br> 
<i><span style="color:#1D1C1D;font-size:11.5pt;font-family:Arial,sans-serif;"> 
This link will keep updating as I rework the design and finish out all the connections…so you can check back on it. It currently still looks like the first design.</span></i><

**Comment by AmyRickwartz** [comment]
[Overall Design in Figma](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field---Current?node-id=4603%3A13352)
Here is a link for hand-off to development.
@CarsonF Let me know if you need any clarification.
