### ISSUE TITLE
Language Engagement Products - Add correct Methodology options

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#719]
Specifically need to update the options for Oral Translation and Oral Storying Approaches as follows:

**Oral Translation Approach**
- Render
- Audacity
- Adobe Audition
- Other Oral Translation

**Oral Stories Approach**
- Story Together
- Seed Company Method
- One Story
- Craft 2 Tell
- Other Oral Stories

Also available here on the wiki: https://github.com/SeedCompany/cord-api-v3/wiki/Approaches-&-Methodologies

**Comment by CarsonF** [comment]
They look right to me. Though the editing InternshipEngagement.methodologies looking poor. The UI could be better.

**Comment by sethmcknight** [comment]
@CarsonF do you have a screenshot you can share? About 45 minutes ago when I was in the training env they were still incorrect.

**Comment by CarsonF** [comment]
![Screen Shot 2021-02-10 at 1 36 24 PM](https://user-images.githubusercontent.com/932566/107562148-0e61d300-6ba5-11eb-89f0-44460644b32f.png)
![Screen Shot 2021-02-10 at 1 36 42 PM](https://user-images.githubusercontent.com/932566/107562149-0efa6980-6ba5-11eb-9664-fab826457206.png)



There were updated here: fc0240725f4a6bffb4013b4a47ccae93492cc26b

**Comment by sethmcknight** [comment]
ok, great! Thank you @CarsonF !

I haven't been able to see that on a live environment yet and needed to confirm. I'll close this out.
