### ISSUE TITLE
Channel Posts/Comments Design

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#721]
Current Phase  – **Ready for Development**

[Current - Comments Design](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field---Current?node-id=4211%3A0) 
Link – Figma file for developers 

- [x] Define 
- [x] Design 
- [x] Review
- [ ] Prototype
- [ ] Test
- [ ] Analyze & Report
- [ ] Review 
- [ ] Design Adjustments (if necessary)

[Draft - Comments Design](https://www.figma.com/file/sWiPVOrIojuU8ityKQAnBP/Draft-Cord-Field?node-id=37%3A115)
Link – Work in progress Figma file

**Comment by sethmcknight** [comment]
Patrick estimated 2 sprints to complete this

**Comment by sethmcknight** [comment]
**Notes From Roadmap**

Description:
Improve staff communication about projects by providing Team Members with a tool to add notes, stories, and prayer requests to each project in CORD Field. This provides a centralized location to capture and share information, and allows us to replace other tools and manual processes in the future.

Requirements:
- Allow users to post an update about a project, selecting from a list of categories
- Initial Categories would include ‘Note’, ‘Story’, and ‘Prayer Request’
- Capture a text field, user who posted, date posted, category and public/private

**Comment by AmyRickwartz** [comment]
### **Kick-Off Meeting Notes**

**Guidelines** 
Needs a time stamp
Can have rich text (emojis)
Can use html coding
Developers will use a free technical library. They are deciding on that now.
Need an update on what free technical library they are going to use.
Technical library example: CK Editor
Looking for a basic design to start with.
    No advanced threading
    No nesting
    No linking
    No quoting automatic function
    Similar to chat in Slack
 
**Types of Posts**
Prayer Request, Note, Story…to start with.
 
**Sensitivity**
Post needs to have a sensitivity assigned to it—possibly inherited from the project.
Sensitivity is "share internally" or "can share externally"
 
Sensitivity guidelines - to develop - Seth and Field need to discuss that more
Sensitivity could be a drop down list with pre-filled options. No option for user to make a custom tag for a post (yet).
 
Michael believes you should never rely on the user for sensitivity. Never just rely on a post that tells someone that this info is sensitive and not to share. Needs to be a built in business rule (coded in program)
 
Can add discussions to anything regardless of content
Doesn't have to be specific to Projects or one thing—specific or generic
Michael thinking: Discussion box at the bottom of the page
 
**Timeline**
Would like designed in 1 sprint / 2 weeks.
 
**Objective**
To get a MVP for posts up on Cord Field as soon as possible. We can change/improve it later.
 
**Cord Field Roadmap**
    Eventually posts will be able to upload files
    Business rules on tags
    Notifications
    Approvals
    App integrations

**Comment by AmyRickwartz** [comment]
**Comments Design – Ready for Development**

[Current - Comments Design](https://www.figma.com/file/IfEmcJeuNY6ucgjYctlKB7/Cord-Field---Current?node-id=4211%3A0)
Link to Figma file for developers

@ParkeBrown @sethmcknight @michaelmarshall @CarsonF

**Comment by sethmcknight** [comment]
Awesome, thanks @AmyRickwartz ! This looks great! 

I'll link this to the dev ticket.
