### ISSUE TITLE
Person Details | Assign & Update Roles

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#722]
Administrators should be able to add, change and remove roles from a Person on the People Details page.

Leverage the existing UI for adding/editing the roles of a Team Member.

<img width="444" alt="Screen Shot 2021-07-09 at 12 43 33 PM" src="https://user-images.githubusercontent.com/7377802/125122920-49fcbc80-e0b3-11eb-8194-d37c42cac9f1.png">

**Comment by CarsonF** [comment]
Cherry picked to master. Going live now.
