### ISSUE TITLE
Add banner or something else to show that training.cordfield is not the prod environment

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#729]

**Comment by CarsonF** [comment]
What's some wording that would make sense for users? Not sure they will understand "live" or "production".
Maybe design would have input?

![Screen Shot 2021-04-06 at 1 35 00 PM](https://user-images.githubusercontent.com/932566/113761290-e7bfa480-96dc-11eb-9d6c-59f336066e33.png)

**Comment by michaelmarshall** [comment]
"This is the training site" makes the info we are trying to convey implicit rather than explicit, and removes the need to agree on wording. My thought.

**Comment by CarsonF** [comment]
I was hoping I could get by without declaring/configuring the environment name so it would work for `dev`, etc as well.

**Comment by sethmcknight** [comment]
@CarsonF I think what you have there works great for now. It should be clear enough that this isn't cordfield.com.

The only change I might make is adding "Data may be reset at any time." like Michael called out but I don't know how important that is.

**Comment by AmyRickwartz** [comment]
I think what Michael was saying makes sense for a _"non-developer user."_ This is what I might suggest:

This site is for training purposes only. Keep data entry generic.
Please use cordfield.com for official reporting.

@CarsonF @michaelmarshall @sethmcknight

**Comment by sethmcknight** [comment]
@CarsonF We could use that 👆 on both environments (even though dev isn't technically for training)
