### ISSUE TITLE
Location > Location menu is not displayed at the menu bar

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#731]
**Roles:** All

**Describe the bug**
Location > Location menu is not displayed at the menu bar

**Steps to Reproduce**
1. Login with admin user

**Expected Result**
Location menu should be displayed

**Actual Result**
Location menu is not displayed at the menu bar
See video - 

https://user-images.githubusercontent.com/5212585/108673395-96cb6680-7509-11eb-9fbc-edafb59a99b2.mp4

 cord-field# 9fa4b368

**Comment by CarsonF** [comment]
This hasn't been asked for. Location's can still be searched or basically to from other pages.

We have lots of resources that aren't in the side bar.

**Comment by ParkeBrown** [comment]
@sethmcknight can you confirm we should refer to you as a possible future feature if desired and resolve

**Comment by sethmcknight** [comment]
This is not a current feature and should not be expected or built at this time.
