### ISSUE TITLE
Remove "TBD Intern" from project

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#739]
User needs helps removing "TBD Intern" from the intern project identified here: https://github.com/SeedCompany/management/issues/41

**Comment by ParkeBrown** [comment]
@blakekrammes I think this could be a candidate based on today's call

cc @sethmcknight

**Comment by blakekrammes** [comment]
The deed is done. @sethmcknight should we make some issues to be able to delete engagements in the UI? Could at least give that power to admins.

**Comment by sethmcknight** [comment]
@blakekrammes thanks! And FYI it already exists ;) seedcompany/cord-field#480

**Comment by blakekrammes** [comment]
Excellent, thanks. I did a quick search on the project board, but didn't find it.
