### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-field#741]
Change from a date to the seed company copyright without a date

**Comment by CarsonF** [comment]
After some research, it's meant to be the date that the work was created. And they say for websites it doesn't really matter, so I would be in favor of just dropping the date.
https://stackoverflow.com/q/2390230/1563719
https://www.reddit.com/r/webdev/comments/1p9tao/auto_updating_the_year_on_copyright_notices

Also shouldn't the name be "Seed Company" not "CORD Field" as it is in our MIT license?

**Comment by CarsonF** [comment]
Closed with 4ea19e057a78f4f8e6df64e1379e0e5f8e5cc262
