### ISSUE TITLE
Remove Alvare and Zavar languages from Faamugo Cluster 2

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#744]
https://github.com/SeedCompany/management/issues/67

**Comment by sethmcknight** [comment]
@michaelmarshall I'm happy to do these if you can provide the mutation I need to use (I can find the ID's)

**Comment by sethmcknight** [comment]
The `Alvare` and `Zavar` language engagements have been deleted from the `Faamugo Cluster 2` project.
