### ISSUE TITLE
Change User Email Address

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#745]
Can you change Davilex Lugo’s email needs to davidlex20@gmail.com

**Comment by blakekrammes** [comment]
Individual problem has been fixed in db. I opened an issue to work that will fix the root issue in the API so that this can be updated via playground by support.

**Comment by ParkeBrown** [comment]
@blakekrammes I see the change in Cord. Is there additional verification of this needed?

**Comment by blakekrammes** [comment]
Thanks for verifying. There isn't.
