### ISSUE TITLE
Login > Getting  "Something wasn't right. Try again, or reset password." error when a user enters valid credentials

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#752]
**Roles:** All

**Describe the bug**
Login > Getting  `Something wasn't right. Try again, or reset password.` error when a user enters valid credentials

**Steps to Reproduce**
1. docker-compose down
2. docker-compose pull db
3. docker-compose up -d db
4. yarn
5. yarn start: dev
6. Login as a root user

**Expected Result**
The user should be logged in.

**Actual Result**
Getting  `Something wasn't right. Try again, or reset password.` error when a user enters valid credentials

See video - 

https://user-images.githubusercontent.com/5212585/110279928-f0e72400-7fff-11eb-87f2-d49640be114a.mp4

**Note:**: 
1. User able to log in from the API side.
2. We also tried cleaning and reset the DB.

cord-field# 26eeba76
cord-api-v3# 44e862f0

**Comment by CarsonF** [comment]
Try 
```
docker-compose up -dV db
```
To recreate the database volume. 
And then restart the API.

**Comment by CarsonF** [comment]
Fixed with https://github.com/SeedCompany/cord-api-v3/commit/474289ae29fa8d38d3164bfea924f7deeece173f
