### ISSUE TITLE
Partnership Card - Primary Partner

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#753]
Add a field to define which Partnership is the 'Primary Partner' (there can only be 1 per Project)

**Comment by sethmcknight** [comment]
@zkhin you're good to move forward with what you have on this issue, we won't have designs for this now.

**Comment by zkhin** [comment]
@CarsonF Can we close this ticket or do we need to wait for the design?

**Comment by CarsonF** [comment]
Up to @sethmcknight

**Comment by sethmcknight** [comment]
@zkhin Just checked this out in Dev, looks great! We can close this out. Thanks so much!
