### ISSUE TITLE
Remove Language from Project

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#758]
Remove the Bata language from the Adamawa Cluster that is in development.

Or suggest GQL query for Parke to use

**Comment by ParkeBrown** [comment]
@sethmcknight given recent guidance, should this be removed?

**Comment by CarsonF** [comment]
```
deleteEngagement
```

**Comment by sethmcknight** [comment]
> @sethmcknight given recent guidance, should this be removed?

This is a different instance since she is actively developing the project.

**Comment by sethmcknight** [comment]
> Remove the Bata language from the Adamawa Cluster that is in development.
> 
> Or suggest GQL query for Parke to use

@ParkeBrown I took care of this one. Here's the mutation:

`mutation {
  deleteEngagement(id:"5ec2d58fafd9ac22ffe528ea")
}`
