### ISSUE TITLE
Product > Created Product details are not displayed on the "Language Engagement Details" page without a refresh

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#759]
**Roles:** All

**Describe the bug**
Product > Created Product details are not displayed on the `Language Engagement Details` page without a refresh

**Steps to Reproduce**
1. Login with root user
2. Click on the `Create a New Item` button and select the `Project` menu
3. Add `Project`detail and click on the `Submit` button
4. Open the created project and add the `Language Engagement`
5. Click on the `Language Engagement ` edit  button and add product details
6. Click on the `Save` button

**Expected Result**
The created product should be displayed on the `Language Engagement Details` page without a refresh

**Actual Result**
 Created Product details are not displayed on the `Language Engagement Details` page without a refresh
See video - 

https://user-images.githubusercontent.com/5212585/111153824-6d59a400-85b8-11eb-8f3d-442ec0f8f710.mp4

cord-field# fe827256

**Comment by ParkeBrown** [comment]
@sethmcknight could you put this on your list to prioritize?
