### ISSUE TITLE
Project > Green padding is not displayed on the "Discuss Reactivation" option while the user changes the status "Suspended" to "DiscussingReActivation"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#760]
**Roles:** All

**Describe the bug**
Project > Green padding is not displayed on the `Discuss Reactivation` option while the user changes the status `Suspended` to `DiscussingReActivation`

**Steps to Reproduce**
1. Login with root user
2. Click on the `Create a New Item` button and select the `Project` menu
3. Add `Project`detail and click on the `Submit` button
4. Change status `Early Conversations` to `Suspended`
5. Click on the `Suspended` status  button 

**Expected Result**
The green padding should be displayed on the `Discuss Reactivation` option 

**Actual Result**
Green padding is not displayed on Discuss Reactivation option while the user changes the status `Suspended` to `DiscussingReActivation`
See video - 

https://user-images.githubusercontent.com/5212585/111423949-10283480-8717-11eb-8f28-73a9cdbb57f7.mp4

cord-field# fe827256

**Comment by CarsonF** [comment]
Each transition has a type of _approve_, _neural_, _reject_. The UI styles the button according to those types. Both of those transitions are considered _neutral_.
