### ISSUE TITLE
Downloading from History is not working for PnP Card

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#767]
https://github.com/SeedCompany/management/issues/110

"the issue is the "download" option from the History information doesn't work.

When I go to the "main" view of the Planning and Progress that shows the last one, it seems to download. But again not from the history view that opens up and has a download option."

**Comment by CarsonF** [comment]
Fixed yesterday with 12729be9dd1779aae421d1786b587674587f4a4a. Deploying to prod now.
