### ISSUE TITLE
Project has gone missing from Production.

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#768]
Work with Nolan and Seth in progress here: https://github.com/SeedCompany/management/issues/113

**Comment by sethmcknight** [comment]
A Project was able to be accessed in production yesterday at: https://cordfield.com/projects/6010309ded7be85699f548ff

This URL now says 'Oops, sorry. Could Not Find Project.' We need to look into why this Project can no longer be found ASAP. Once we identify the root cause we need to check if any other Projects have had the same thing happen.

**Comment by blakekrammes** [comment]
The project has been deleted. This is only doable through playground, right?

**Comment by sethmcknight** [comment]
@blakekrammes yeah I think that's only through Playground, we don't have anything in the UI to allow users to delete Projects.

Do we have any logs to show when it was deleted and who deleted it? Assuming this was done manually by one of us I want to track down where the request came from.

**Comment by sethmcknight** [comment]
@blakekrammes super glad to hear we aren't actually deleting anything from the db though! If you could restore that Project that would be great!

**Comment by blakekrammes** [comment]
Yeah. I should probably write up the inverse of the delete function to make this super easy.

**Comment by blakekrammes** [comment]
Looking for API logs.

**Comment by blakekrammes** [comment]
So there was no `DeleteProject` operation sent to the API, but there was a `DeleteFileNode` called on the project's root directory. Since it shares the same id as the project I think it deleted both since we only match base nodes by id on delete. This happened around 3:27pm yesterday.

**Comment by blakekrammes** [comment]
Any user that has file permissions on the project could do this.

**Comment by sethmcknight** [comment]
@blakekrammes yikes! Is the project's root directory the `/` directory that is visible? How else would they be able to delete the root directory?

**Comment by blakekrammes** [comment]
Yes. That's the one.

**Comment by sethmcknight** [comment]
Yeah, we should fix that! Haha.

Are you able to restore that directory?

**Comment by blakekrammes** [comment]
Yes. Will also need to restore the project manually for now. 
- We should add some more checks on delete to see if it's a project or directory. That will prevent this from happening again. 

- Also might be worth writing an inverse function to make this easy as mentioned above

**Comment by ParkeBrown** [comment]
Would this be an example case where we should spell out the right way to do it in the meantime?
https://github.com/SeedCompany/management/issues/111

**Comment by sethmcknight** [comment]
> Would this be an example case where we should spell out the right way to do it in the meantime?
> [SeedCompany/management#111](https://github.com/SeedCompany/management/issues/111)

@ParkeBrown I don't think so. This should be the existing query for deleting an Engagement.

It looks like the issue with this Internship Project is the migrated `/` folder was deleted. Because it has the same ID as the Project, the Project ended up being deleted as well. Any user is able to delete folders.

**Comment by blakekrammes** [comment]
Yeah. Also thinking through it more, after we remove the superfluous root dirs, we should just prohibit deletion of the root directory.

**Comment by CarsonF** [comment]
> So there was no `DeleteProject` operation sent to the API, but there was a `DeleteFileNode` called on the project's root directory.

Operation names are not defined by the API, but rather the requestor. So the lack of an op name in the logs doesn't mean it didn't happen. We mostly don't bother when writing queries manually in playground.
```gql
mutation { // <-- no operation name
  deleteFileNode()
}
mutation CreateFileNode {
  deleteFileNode()
}
```

---

The root dirs used to share the same ID as the project, they don't any more. The `/` folder you are seeing in the UI is not the root directory. It's a sub directory under the project's root directory. We don't allow deleting root directories from UI FWIW.

**Comment by blakekrammes** [comment]
Ah. You're right. My bad. The root directory is intact. Is there another way to find out how the project was deleted in the logs? I was looking by project id.

**Comment by blakekrammes** [comment]
Well actually my point still kind of stands since the old migrated root directory does share the project id. That was the file node deleted and the same operation `DeletedFileNode` that deleted the project since those had the same id.

**Comment by blakekrammes** [comment]
![Uploading Screen Shot 2021-03-24 at 11.11.33 AM.png…]()

**Comment by CarsonF** [comment]
Yeah we should've gotten rid of those weeks ago.

**Comment by blakekrammes** [comment]
Right. It didn't seem to be a high priority. This is making me reconsider.

**Comment by blakekrammes** [comment]
Project is restored and the migrated V2 root dirs are gone, so this problem should happen again. 

Closes https://github.com/SeedCompany/cord-api-v3/issues/1658
