### ISSUE TITLE
Project > Upload file > Getting "TypeError: Cannot assign to read only property '0' of object '[object Array]'" error while delete the "New version" file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#777]
**Roles:** Admin

**Describe the bug**
Project > Upload file > Getting `TypeError: Cannot assign to read only property '0' of object '[object Array]'` error while delete the `New version` file

**Steps to Reproduce**
1. Login as an admin user
2. Create a new project 
3. Click on the upload file button and upload a new file
4. Click on the newly created file kebab menu and add `new version` of the file
5. Click on the newly created file kebab menu and click on the `History` button
6. Click on the `History` kebab menu and click on the `Delete` button

**Expected Result**
The new version of the file should be deleted

**Actual Result**
Getting `TypeError: Cannot assign to read-only property '0' of object '[object Array]'` error while delete the `New version` file

See video - 

https://user-images.githubusercontent.com/5212585/113131495-ebfe4480-923a-11eb-87f1-689d74df21fd.mp4

cord-field# 5a2c4107

**Comment by CarsonF** [comment]
@iPiyushPatel I fixed the code that resulted in the crash. I believe the file history list is still bugged to not remove the item. I'm going to rebuild most of the file components in the next few days to be built on my new list caching code. It should be fixed after that.
