### ISSUE TITLE
Update `Search` field to make the Search icon a `Submit` button

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#778]
┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466725479) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
Fixed with 25656a9

**Comment by sethmcknight** [comment]
@CarsonF this either didn't get deployed to Dev, isn't working, or I need to be shown how this works.

**Comment by CarsonF** [comment]
It's not a button but when clicked it will focus the input field. What exactly is it doing for you? Maybe refresh?

**Comment by sethmcknight** [comment]
> It's not a button but when clicked it will focus the input field. What exactly is it doing for you? Maybe refresh?

Oooohhh, sorry @CarsonF I don't think my description was clear.

We have users who are clicking in the search input field, typing in a search, and then trying to click the magnifying glass search icon to initiate the search instead of hitting enter on their keyboard.

I'd like to have that search icon be a button that users can click to initiate a search as an alternative to hitting enter on their keyboard to do the search.

**Comment by CarsonF** [comment]
Oh they want it to be a submit button. Got it.
