### ISSUE TITLE
Display Data for Latest File Version

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#786]
When a new version of a file is uploaded it can be previewed or downloaded from the main files scene or the file history modal.

The data that is displayed on the main files scene is currently always the original file version.

We should update this so that the data for the latest file version is displayed on the main files scene. We are already doing this on Defined Files.

File Data:
- Name
- Created (should we change to Modified?)
- Uploaded By
- File Size

**Comment by CarsonF** [comment]
We should be updating it, maybe it's a cache bug. Does it change on refresh?

**Comment by sethmcknight** [comment]
@CarsonF nope, and when I went to one of the Projects to check the files it just showed the original version details, even though there are 2 more recent versions.

**Comment by sethmcknight** [comment]
This applies to files in the main project directory as well as the Planning Spreadsheet, Universal Budget Template, and Periodic Reports.

**Comment by tmpacifitech** [comment]
@sethmcknight I tested file version preview for Project Files, Planning Spreadsheet, Universal Budget Template, and Periodic Reports and confirmed this was already fixed on dev site.

**Comment by CarsonF** [comment]
Ok we are going to:
- [ ] Rename file, if applicable, when a new version is created
- [ ] Show modified at & by in UI instead of created at & by

**Comment by sethmcknight** [comment]
@tmpacifitech thanks! This looks great and I know a bunch of our users will be very happy when we push this to Prod!
