### ISSUE TITLE
Add download button to the file preview window

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#792]
When users preview a file, they have to close the preview and open the overflow menu to download the file.

We need to add a button to the file previewer that will allow a user to download the file they are previewing without having to close out of the previewer and open the overflow menu.

**Comment by sethmcknight** [comment]
Designs:

<img width="567" alt="Screen Shot 2021-11-04 at 12 08 34 PM" src="https://user-images.githubusercontent.com/7377802/140395654-0b88475b-f69b-4bb5-8cf5-8ed9d18a4045.png">
<img width="505" alt="Screen Shot 2021-11-04 at 12 09 00 PM" src="https://user-images.githubusercontent.com/7377802/140395660-b2a69912-f1fa-4f8b-bde9-ff209ae4c6ec.png">
<img width="470" alt="Screen Shot 2021-11-04 at 12 09 07 PM" src="https://user-images.githubusercontent.com/7377802/140395662-ec7a5eba-06cb-4377-8d6b-473d04446b6b.png">
<img width="474" alt="Screen Shot 2021-11-04 at 12 09 17 PM" src="https://user-images.githubusercontent.com/7377802/140395664-405a245d-572e-49f2-b13c-c7f3b8ba1a60.png">

**Comment by CarsonF** [comment]
I'm good with all of this, except print and download all. Let's just try to tackle the second image as first step.

**Comment by tmpacifitech** [comment]
> I'm good with all of this, except print and download all. Let's just try to tackle the second image as first step.

@CarsonF I tackled the second image.. what next step do you want me to go on?
