### ISSUE TITLE
Project > Partnership > Getting "Cannot read property 'value' of undefined" error while creating/editing the partnership

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#817]
**Roles:** All

**Describe the bug**
Project > Partnership > Getting `Cannot read property 'value' of undefined` error while creating/editing the partnership

**Steps to Reproduce**
1. Login as Admin user
2. Create a new Project 
3. Click on the `Partnerships` button and create a new partnership
4. Back to the project detail page and again click on the `Partnerships` button

**Expected Result**
The partnership should be created/edited

**Actual Result**
Getting `Cannot read property 'value' of undefined` error while creating/editing the partnership

See video - 

https://user-images.githubusercontent.com/5212585/115010796-b07e8f80-9e62-11eb-9da7-bdb75eb238bd.mp4

cord-field# fdfb7698

**Comment by ParkeBrown** [comment]
Noted with ASMs to final test

**Comment by mosesintech** [comment]
I was not able to reproduce this bug after many attempts. Could there be a step missing from the list and/or the video?

**Comment by iPiyushPatel** [comment]
Hi @mosesintech @CarsonF @ParkeBrown 
I've verified on latest develop 71c8ecb5 and it's working fine feel free to close it.
See video:  

https://user-images.githubusercontent.com/5212585/115342356-fc7d4d00-a15e-11eb-8c59-194bff8fd6c3.mp4


thanks

**Comment by ParkeBrown** [comment]
@iPiyushPatel thanks!
