### ISSUE TITLE
Crash on Product detail

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#821]
**Engagement:** 5c4278fe9503d5cd78e83fad
**Log Rocket:** https://app.logrocket.com/x6d22y/cord-prod/s/4-45ec6fe0-37fd-4e56-892f-90b8a6b81601/0?filters=%255B%257B%2522id%2522%253A%2522SyJ6wIjLd%2522%252C%2522type%2522%253A%2522href%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522https%253A%252F%252Fcordfield.com%252Fprojects%252F5c4278fe9503d5cd78e83fad%252Fengagements%252F5c4279179503d5cd78e85438%252Fproducts%252F5ea82eab2257df829a28df18%2522%255D%257D%255D&fromTab=latest&t=1618848211551.9507
**Sensitive Details:** https://github.com/SeedCompany/management/issues/157

**Comment by ParkeBrown** [comment]
**sethmcknight** 
Here's a representative Product in Production https://cordfield.com/projects/5d2de693abc8f499add79463/engagements/5d2de6daabc8f42cfed79505/products/5ebc1159ba4acfa32f555b4f

And here's one in Dev https://dev.cordfield.com/projects/g26CWMNOcBB/engagements/v18B1JO20lx/products/JEb1pZTmmGU

**Comment by ParkeBrown** [comment]
This seems to have been adequately reproduced by Seth, meaning it's ready for a developer.

**Comment by elisabeth-sorrell** [comment]
looks like the fix needs to be applied to the front end
from what I could something is expecting data for `produces`  when it's a `DirectScriptureProduct`, which apparently shouldn't have a `produces`  field when the api isn't spitting out a produces field at all. 
Talked to Carson and he says it's a UI problem

**Comment by CarsonF** [comment]
Did the PR fix this?
