### ISSUE TITLE
Project > Team member > Getting "Sorry, you don't have permission to view this project's team members." error message even "Financial Analyst" user has global read access of team member

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#822]
**Roles:** Financial Analyst

**Describe the bug**
Project > Team member > Getting `Sorry, you don't have permission to view this project's team members.` error message even `Financial Analyst` user has global read access of team member

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Add `Project manager` as a team member 
4. Logout the admin user and log in as a financial analyst user
5. Click on the `Team Members` button
6. Back to the project details page

**Expected Result**
The valid error message should be displayed as per permissions

**Actual Result**
Getting `Sorry, you don't have permission to view this project's team members.` error message even `Financial Analyst` user has global read access of team member

See video - 

https://user-images.githubusercontent.com/5212585/115709243-d524ac80-a325-11eb-88e3-ce9ba79615e2.mp4

![image](https://user-images.githubusercontent.com/5212585/115714486-02745900-a32c-11eb-8a3f-3556bba471c1.png)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 71c8ecb5

**Comment by ParkeBrown** [comment]
Thanks!
We added it on to this: https://github.com/SeedCompany/cord-api-v3/issues/1830
Per Carson it’s the same issue and should be resolved by this: https://github.com/SeedCompany/cord-api-v3/issues/1653
Once he finishes this: https://github.com/SeedCompany/cord-api-v3/issues/1736
