### ISSUE TITLE
Project > Team member > "Add Partnership" button is displayed even team member is removed from "Financial Analyst" user

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#823]
**Roles:** Financial Analyst

**Describe the bug**
Project > Team member > `Add Partnership` button is displayed even team member is removed from `Financial Analyst` user 

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Login as a `Financial Analyst` user and click on the `Partnership` button
4. Logout the `Financial Analyst`  user and log in as an `Admin` user
5. Click on the `Team Members` button
6. Add  `Financial Analyst` as a team member
7. Login as a `Financial Analyst` user
8. Click on the `Partnership` button
9. Back to the project detail page and removed `Financial Analyst` user from team member
10. Again click on the `Partnership` button

**Expected Result**
 `Add Partnership` button should not be displayed after removing the `Financial Analyst` team member

**Actual Result**
 `Add Partnership` button is displayed even team member is removed from the `Financial Analyst` user 

See video - 

https://user-images.githubusercontent.com/5212585/115718533-0c985680-a330-11eb-8bcc-005083d00a2e.mp4

![image](https://user-images.githubusercontent.com/5212585/115718831-5b45f080-a330-11eb-9299-28943a87cf38.png)

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 71c8ecb5

**Comment by parashara1** [comment]
Was able to reproduce the bug, followed steps to reproduce and the "Add Partnership" button is still present before and after removing the "Financial Analyst" user from team members. Expected result according to Piyush would be the "Add Partnership" not being displayed.
