### ISSUE TITLE
Consultant Gets Error "Cannot read property 'status' of undefined" When Opening Any Project

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#832]
One particular Consultant is getting this error on every engagement page he tries to visit. I cannot reproduce in live, but I have observed on screen share. User says he's been experiencing issues like this for two weeks though bug report is from last four days +-.

**User:** https://cordfield.com/users/5c5dfbd41e560f7f00c0a60f
**Engagements:** (All assigned to him, but first two on the list are 5d2de693abc8f499add79463 and 5d3ee7e2abc8f41d07e331c4 )
**Error screenshot:**
![116917970-541abe80-ac1d-11eb-960b-5cf5c6bab9df](https://user-images.githubusercontent.com/5691814/116924798-57ff0e80-ac26-11eb-8129-63a3320e30d2.png)
**Log Rocket Log:** https://app.logrocket.com/x6d22y/cord-prod/s/4-86dd486a-24ee-43db-a466-fb3726a9a268/0?filters=%255B%257B%2522id%2522%253A%2522SJOG95uwd%2522%252C%2522type%2522%253A%2522email%2522%252C%2522operator%2522%253A%257B%2522name%2522%253A%2522is%2522%252C%2522type%2522%253A%2522IS%2522%252C%2522hasStrings%2522%253Atrue%252C%2522autocompleteEnabled%2522%253Atrue%257D%252C%2522strings%2522%253A%255B%2522paul_schmidt%2540tsco.org%2522%255D%257D%255D&fromTab=latest

**Comment by ParkeBrown** [comment]
Support conversation: https://github.com/SeedCompany/management/issues/164

**Comment by blakekrammes** [comment]
I've reproduced locally with his account in a prod-like environment. Investigating further.

**Comment by blakekrammes** [comment]
From Slack:

We have two roles in the db, `BibleTranslationLiaison` and `Liaison`. I’m guessing we replaced the former with the latter and forgot to update the role in the db. It doesn’t look like `BibleTranslationLiaison` is implemented as a role in the API. I updated the user’s role to `Liaison` in a test environment and am able to view projects now, but I want to confirm that this is the same role. There are only 9 users who have this role in the db.
I checked the closed issues where we remapped old roles and these two weren’t mentioned.

**Comment by ParkeBrown** [comment]
I've changed his role in production to Liaison, which seems to be correct.

Confirming with user.

**Comment by ParkeBrown** [comment]
Checking with user again

**Comment by ParkeBrown** [comment]
I plan to close this with the end of the sprint as we've had no further feedback from the user.

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on the latest develop e8bb4ac and can't reproduce this issue.
See video:

https://user-images.githubusercontent.com/5212585/134857276-c5ef9e21-b530-4767-945f-3c833416c5c2.mp4
