### ISSUE TITLE
Project > Comments > Getting "TypeError: Cannot read property 'map' of undefined" error when the user clicks on the "Add comment" button

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#834]
**Roles:** All

**Describe the bug**
Project > Comments > Getting `TypeError: Cannot read property 'map' of undefined` error when the user clicks on the `Add comment` button

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Open Created project
4. Click on the `Add  comment` button

**Expected Result**
A comment box should be displayed.

**Actual Result**
Getting `TypeError: Cannot read property 'map' of undefined` error when the user clicks on the `Add comment` button.

See video - 

https://user-images.githubusercontent.com/5212585/116966695-64d73d00-acce-11eb-8b22-992b33cdeaed.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 1e7d5d88

**Comment by parashara1** [comment]
Successfully reproduced the bug, admin user cannot "add comment". When attempting to click the "Add Comment" button, the error "TypeError: Cannot read property 'map' of undefined" is returned
