### ISSUE TITLE
Project > Language engagement > Getting "Unknown function 'apoc.coll.flatten' (line 3, column 8 (offset: 279)) "RETURN apoc.coll.flatten(collect(roles.value)) AS memberRoles" ^" error when the user create a language engagement

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#836]
**Roles:** All

**Describe the bug**
Project > Language engagement > Getting `Unknown function 'apoc.coll.flatten' (line 3, column 8 (offset: 279)) "RETURN apoc.coll.flatten(collect(roles.value)) AS memberRoles" ^` error when the user create a language engagement

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Open Created project
4. Click on the `Add language engagement` button
5. Enter language name and click on submit button

**Expected Result**
Language engagement should be created.

**Actual Result**
Getting `Unknown function 'apoc.coll.flatten' (line 3, column 8 (offset: 279)) "RETURN apoc.coll.flatten(collect(roles.value)) AS memberRoles" ^` error when the user create a language engagement.

See video - 

https://user-images.githubusercontent.com/5212585/117098813-20f73d00-ad8d-11eb-9dc8-57cea6c2a7af.mp4

**StackTraces:**
```
{
  "errors": [
    {
      "message": "Unknown function 'apoc.coll.flatten' (line 3, column 8 (offset: 279))\n\"RETURN apoc.coll.flatten(collect(roles.value)) AS memberRoles\"\n                    ^",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "N/A",
          "name": "SyntaxError",
          "stacktrace": [
            "at Session.run (core\\database\\cypher.factory.ts:180:20)"
          ]
        },
        "codes": [
          "INTERNAL_SERVER_ERROR",
          "Server"
        ]
      },
      "locations": [
        {
          "line": 52,
          "column": 3
        }
      ],
      "path": [
        "createLanguageEngagement",
        "engagement",
        "products"
      ]
    }
  ],
```
**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 1e7d5d88

**Comment by parashara1** [comment]
Successfully reproduced the issue. Admin user is unable to add a "language engagement" to an existing project. Error message: "Unknown function 'apoc.coll.flatten' (line 3, column 8 (offset: 279)) "RETURN apoc.coll.flatten(collect(roles.value)) AS memberRoles" is being returned.

**Comment by CarsonF** [comment]
It's a problem with your database. You don't have APOC installed or maybe it's too old.

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
We're using Docker now, so not sure how APOC is related. Can you please advise what I'm missing here?
