### ISSUE TITLE
Project > Post > Getting "Variable "$input" got invalid value "Public" at "input.post.shareability"; Value "Public" does not exist in "PostShareability" enum." error when user select  "public" as a "Shareability"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#840]
**Roles:** All

**Describe the bug**
Project > Post > Getting `Variable "$input" got invalid value "Public" at "input.post.shareability"; Value "Public" does not exist in "PostShareability" enum.` error when user select  `public` as a `Shareability`

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Open Created project
4. Click on the `Add  post` button
5. Select `Shareability` as a public 
6. Add a comment in the comment box and click on the `post comment` button

**Expected Result**
Comment should be submitted

**Actual Result**
 Getting `Variable "$input" got invalid value "Public" at "input.post.shareability"; Value "Public" does not exist in "PostShareability" enum.` error when user select  `public` as a `Shareability`

**FYI:**
The same issue is produced for `Ask To Share Publicly` option

See video - 

https://user-images.githubusercontent.com/5212585/117433144-ca366280-af48-11eb-8511-60cade780938.mp4

**Stack traces**
```
{
  "errors": [
    {
      "message": "Variable \"$input\" got invalid value \"Public\" at \"input.post.shareability\"; Value \"Public\" does not exist in \"PostShareability\" enum.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": []
        },
        "codes": [
          "INTERNAL_SERVER_ERROR",
          "Server"
        ]
      },
      "locations": [
        {
          "line": 1,
          "column": 21
        }
      ]
    }
  ],

```

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 23c576e9

**Comment by CarsonF** [comment]
Still a problem?

**Comment by iPiyushPatel** [comment]
Hi @CarsonF  
No, Not currently feel free to close it.
