### ISSUE TITLE
Project > Getting "Unhandled Rejection (TypeError): Cannot read property 'type' of null" error when user "Download" an unuploaded "financial report"

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#841]
**Roles:** All

**Describe the bug**
Project > Getting `Unhandled Rejection (TypeError): Cannot read property 'type' of null` error when user `Download` an unuploaded `financial report`

**Steps to Reproduce**
1. Login as an admin user
2. Create a new Project 
3. Open Created project
4. Click on the `Start-End` date button
5. Select `Start-End` date and click on the `submit` button
6. Click on `Finacial report` 
7. Click on the `kebab` menu and download the file

**Expected Result**
A valid error message should be displayed.

**Actual Result**
Getting `Unhandled Rejection (TypeError): Cannot read property 'type' of null` error when user `Download` an unuploaded report 

**FYI:**
The same issue is produced for `Narrative Report`

See video - 

https://user-images.githubusercontent.com/5212585/117609285-5a5ced80-b17d-11eb-9022-47679faba3bc.MP4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 23c576e9

**Comment by parashara1** [comment]
Successfully reproduced the bug. Admin User is getting "Unhandled Rejection (TypeError): Cannot read property 'type' of null" error when trying to download Financial Report. Same error occurs for the Narrative report as mentioned by Piyush. Changing the start/end dates does not affect outcome.

**Comment by CarsonF** [comment]
Fixed with #865
