### ISSUE TITLE
Project > Field Budget > Universal Template options popup is not dismissed automatically when selecting New Version option

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#847]
**Roles:** All

**Describe the bug**
Project > Field Budget > Universal Template options popup is not dismissed automatically when selecting `New Version`  option

**Steps to Reproduce**

1. Login as an Project Manager
1. Create a new Project and go to project details page
1. Click on the `Budget Details` button
1. Click on the `Add Universal Template` button and upload any file.
1. Click on the kebab menu button of Universal Template
1. Select `New Version` option and upload another file.

**Expected Result**
Universal Template options popup should automatically dismiss when selecting `New Version`  option.

**Actual Result**
Universal Template options popup is not dismissed automatically when selecting `New Version`  option.

See video - 

https://user-images.githubusercontent.com/5212585/118076304-6b04a200-b3cf-11eb-9ce3-e38f206ff8b4.mp4

**FYI:** ParkeBrown michaelmarshall

cord-field# 1d6e8100

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466736056) by [Unito](https://www.unito.io)

**Comment by parashara1** [comment]
While logged in as "Project Manager", selecting "New Version" option does not dismiss the universal template options pop-up

**Comment by CarsonF** [comment]
Related to #913
