### ISSUE TITLE
Intern > Getting "Cannot read property 'status' of undefined" error when user open the project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#858]
**Roles:** Intern

**Describe the bug**
Intern > Getting `Cannot read property 'status' of undefined` error when user open the project

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and go to the project detail page
3. Add `Intern` user as a team member
4. Login as an Intern user
5. Open created project

**Expected Result**
The project should be opened

**Actual Result**
Getting `Cannot read property 'status' of undefined` error when user open the project

See video - 

https://user-images.githubusercontent.com/5212585/120150994-60d50700-c209-11eb-9df7-94616db71984.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 982df0a5

**Comment by CarsonF** [comment]
A stacktrace would be helpful

**Comment by iPiyushPatel** [comment]
Hi @CarsonF 
Currently working fine on latest develop b3285bdb 

https://user-images.githubusercontent.com/5212585/124081740-8607a000-da69-11eb-8d32-6bc4872b89d3.mp4

Feel free to close it.

**Comment by CarsonF** [comment]
Great I probably fixed it somewhere recently 🙂
