### ISSUE TITLE
Login > Getting "Response code 503(ServiceUnavailable)" error intermediate while login any user

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#863]
**Roles:** All

**Describe the bug**
Login > Getting `Response code 503(ServiceUnavailable)` error intermediate while login any user

**Steps to Reproduce**
Login any user 

**Expected Result**
User should be logged in.

**Actual Result**
Getting `Response code 503(ServiceUnavailable)` error intermediate while login any user
 
**Login:**
![image](https://user-images.githubusercontent.com/5212585/121175318-89e44000-c878-11eb-9c9f-ffda75367ba5.png)

**Note:** Issue frequency is around 40-50%

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# fd0a52d4

**Comment by ParkeBrown** [comment]
@iPiyushPatel any other factors that seem to be affecting who could log in and not on this test?

**Comment by ParkeBrown** [comment]
Also helpful to know time range of test in case there is crossover with Fastly outage.

**Comment by iPiyushPatel** [comment]
HI @ParkeBrown  No found any specific factor to affecting the issue but I faced this issue during the testing and after some time it's not replicating. I'll keep eye on the issue and update here if found any particular time frame or steps to reproduce the issue. Thanks!

**Comment by parashara1** [comment]
Haven't been able to replicate this issue yet with my logins. Will keep periodically attempting.

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I've verified on latest develop e8bb4ac and can't reproduce this issue
See video :

https://user-images.githubusercontent.com/5212585/134922289-e966e20c-2c6a-4322-9bf3-2a90523bc414.mp4
