### ISSUE TITLE
Upload Growth Plan GraphQL error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#864]
**Roles:** Admin

**Describe the bug**
Project > Internship  engagement > Getting `Variable "$growthPlan" of required type "CreateDefinedFileVersionInput!" was not provided.`  error when user add  `Growth Plan`  file 

**Steps to Reproduce**
1. Login as Admin user
2. Create an internship project and go to the project detail page
3. Open created project
4. Click on the `Add internship engagement` button
5. Add `Project Manager` user and click on the `submit button
6. Open created internship and `Growth plan` file

**Expected Result**
`Growth Plan` file should be uploaded

**Actual Result**
Getting `Variable "$growthPlan" of required type "CreateDefinedFileVersionInput!" was not provided.` error when a user adds the `Growth Plan` file.

See video - 

https://user-images.githubusercontent.com/5212585/121307939-244a8f00-c91e-11eb-9aa5-f8a15e67b558.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# fd0a52d4

**Comment by CarsonF** [comment]
Regresssed with f98c96f0f29e650d715d0f56f338762495050e6f
