### ISSUE TITLE
Material UI v5

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#867]
Material UI is rolling out their next major version in the next couple months. Beta starts in July.
The upgrade is not critical but needs to be prioritized at some point.

What's new/different?
- They have completely changed the way the styling is done. JSS -> Emotion. This represents a huge change for us, as we follow suit with them. This means a potential migration of _all_ our components.
- Along with this though is a new way to customize their components. For instance, in so many cases we just want to add spacing around layout pieces. This needed a CSS class to do so. Now from my understanding it can simply be added as a property on the component. This results in reduced boilerplate for common styling needs.
- Theme _Color Palettes_ can be customized. Instead of the standard _primary, secondary_, we can now add whatever we want. This is great. We can now have a "create" color palette for all things that...create. This palette can just be pick as property on all MUI components accepting color. Currently we need custom components to wrap and add this functionality.
- Date Pickers are currently cobbled together by us and are basically unsupported. In v5, these are built in.

As the release gets closer they'll have more documentation and upgrade paths. I can take some time then to determine a game plan for what needs to be done and how the work can be divided up.

**Comment by CarsonF** [comment]
[v5 just released](https://mui.com/blog/mui-core-v5/)

**Comment by ParkeBrown** [comment]
@AmyRickwartz would you look at this when you're able?
