### ISSUE TITLE
Project > Getting "TypeError: Cannot read property 'value' of undefined " error when navigating to created Project's details page

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#879]
**Roles:** All

**Describe the bug**
Project > Getting ` TypeError: Cannot read property 'value' of undefined ` error when navigating to created Project's details page

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and go to the project detail page
3. Search created project
4. Open created project

**Expected Result**
User should be redirected to the Project details page.

**Actual Result**
Getting ` TypeError: Cannot read property 'value' of undefined ` error when navigating to created Project's details page.

See video - 

https://user-images.githubusercontent.com/5212585/123908945-ee854d00-d995-11eb-8d22-8010de2428f4.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# cd8498f3

**Comment by parashara1** [comment]
Successfully reproduced bug, getting `TypeError: Cannot read property value of undefined` when admin user tries to access the project detail page.

**Comment by CarsonF** [comment]
Should be fixed with #881
