### ISSUE TITLE
Project > "Start - End" date label is not displayed

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#883]
**Roles:** All

**Describe the bug**
Project > `Start - End` date label is not displayed

**Steps to Reproduce**
1. Login as an Admin user
2. Create a project and open a detail page

**Expected Result**
`Start-End` date label should be displayed

**Actual Result**
`Start - End` date label is not displayed.

See video - 

https://user-images.githubusercontent.com/5212585/124104253-b35f4880-da7f-11eb-8ba3-ee9a08f106db.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# b3285bdb

**Comment by CarsonF** [comment]
Duplicate of #880
