### ISSUE TITLE
Change Requests | Bug with Products

### ISSUE THREAD

**Issue by blakekrammes** [SeedCompany/cord-field#894]
I've noticed that during a change request I can't select specific books as part of the change request. 

<img width="679" alt="Screen Shot 2021-07-16 at 11 20 23 AM" src="https://user-images.githubusercontent.com/49688912/125978839-772c79f2-52fc-4273-825e-7ba4f222c582.png">

However, I can add or delete a product during a change request with no warning that it will not apply to the change request and will be created/deleted immediately. 

I'm not sure what the expected behavior is so this may not actually be a bug. From looking at Ken's [request](https://github.com/SeedCompany/seed-api/issues/139) for the Domo API it looks like he's expecting to have products be a part of change requests. Maybe it just hasn't been implemented yet.

**Comment by ParkeBrown** [comment]
@sethmcknight have you looked at this to confirm expected behavior? Marked as bug in meantime.

**Comment by sethmcknight** [comment]
I wouldn't classify this as a bug just yet, but it does need to be implemented before we roll out.

**Comment by CarsonF** [comment]
Expected as products have not implemented changesets yet
