### ISSUE TITLE
Person Details | Give Admins and Users the ability to edit 'email address'

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#897]
While a Persons email address can be viewed in the Person Details edit modal, the field is disabled for Administrators and the current logged in users.

Today the only way to edit a Person's email address is via GrapQL.

Update the Person Details edit modal to allow Administrators to edit any Persons email address.

Also, allow the current User to edit their email address.

**Comment by CarsonF** [comment]
Fixed with #887

**Comment by sethmcknight** [comment]
@CarsonF I just tried this in Dev and can't seem to get it to work.

To confirm, I should be able to go to a Person's Details, click the edit icon, and change their email address from the existing email to another. Is that correct?

For example from seth_mcknight@tsco.org to seth_intern@tsco.org.
