### ISSUE TITLE
 Login Page > Login screen is shown momentarily when user refresh the page from any screen 

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#899]
**Roles:** All

**Describe the bug**
 Login Page > Login screen is shown momentarily when user refresh the page from any screen 

**Steps to Reproduce**
1. Login as an Admin user
2. Refresh the current page

**Expected Result**
 Login screen should not be shown momentarily

**Actual Result**
 Login screen is shown momentarily when user refresh the page from any screen 

**See video** - 

https://user-images.githubusercontent.com/5212585/126768073-1bf98022-8d82-45ed-80bf-687fe3c71a54.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# dcb47ad

**Comment by CarsonF** [comment]
I can't reproduce this. @parashara1 maybe you can?

**Comment by iPiyushPatel** [comment]
Hi @ParkeBrown @CarsonF @parashara1 
I can still replicate the issue on the latest develop e8bb4ac.
See video: 

https://user-images.githubusercontent.com/5212585/134856208-221213ba-2b50-4435-be87-c355f3fcdc8f.mp4
