### ISSUE TITLE
Create Organization Scene

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-field#90]
- [ ] Create `scenes/Organizations/Organizations.tsx`
  - This component will be the sub routing for `/organizations/*`
  - Connect it to `Root` component
  - `Authentication` is a comparable example
- [ ] Create `scenes/Organizations/Create/...`
  - [ ] `CreateOrganizationForm.tsx` (comparable to `LoginForm`)
  - [ ] storybook file for above
  - [ ] Create `queries.graphql` with create org mutation
  - [ ] `CreateOrganization` connecting form to mutation hook (comparable to `Login`)
- [ ] All folders should have `index.ts` files exporting what is used externally (storybook doesn't count)

**Comment by michaelmarshall** [comment]
I'm unassigning this so I can work on the api security group issue. My branch is `org-scene`.
