### ISSUE TITLE
Project > "Start" and "End" date calendar overlapped while user select year, month, and date from the calendar

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#900]
**Describe the bug**
Project > `Start` and `End` date calendar overlapped while user select year, month, and date from the calendar

**Steps to Reproduce**

1. Login as Admin user
1. Create a project and Click on the `Start` date calendar
1. Click on the `End` date calendar

**Expected Result**
 `Start` and `End` date Calendar should not be overlapped

**Actual Result**
 `Start` and `End` date calendar overlapped while the user select year, month, and date from the calendar.

See video - 
https://user-images.githubusercontent.com/5212585/126781231-6fcfe8de-8121-427e-9eb1-646ac1ad9ab2.mp4

**FYI:** ParkeBrown michaelmarshall

cord-field# dcb47ad

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466795193) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
Related to #686

We don't necessarily want to block certain dates as the user could be wanting to change both. But yeah the range as a whole needs to be validated, which is #686.
