### ISSUE TITLE
createProduct > Scripture > "Placeholder" text missing in "Choose your chapters" Popup.

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#906]
**Roles:** All

**Describe the bug**
createProduct > Scripture > `Placeholder` text missing in `Choose your chapters` Popup.

**Steps to Reproduce**
1.  Login as an Admin user
2.  Create a project and add a `language engagement`
3.  Click on the `view details` button and Add `Product`  
4.  Select a `scriptureReference` and select the start-end book

**Expected Result**
`PlaceHolder` text  should be displayed

**Actual Result**
 `Placeholder` text missing in `Choose your chapters` Popup.

See video - 

https://user-images.githubusercontent.com/5212585/127437128-31650942-6537-41fc-b87a-29ffe3cca531.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 9ef5397

**Comment by CarsonF** [comment]
Hmm that hasn't been touched since January. Do you have a screenshot of what you are talking about?

**Comment by ParkeBrown** [comment]
@CarsonF probably off here but I see a video above. Are you looking for a screenshot of the expected outcome?

**Comment by CarsonF** [comment]
Yeah

**Comment by iPiyushPatel** [comment]
@CarsonF  Please find attached a screenshot 

![image](https://user-images.githubusercontent.com/5212585/127608891-5f6adc50-21fa-47e8-901e-6164b6603cbf.png)

**Comment by CarsonF** [comment]
@blakekrammes What was the expected text here?

**Comment by blakekrammes** [comment]
My bad. Here's a PR: https://github.com/SeedCompany/cord-field/pull/915

**Comment by CarsonF** [comment]
Fixed with #915
