### ISSUE TITLE
createProduct > Scripture > "Product selection required" validation message is displayed when user collapsed "Choose Product" field even scripture is selected

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#907]
**Roles:** All

**Describe the bug**
createProduct > Scripture > `Product selection required` validation message is displayed when user collapsed 'Choose Product' field even scripture is selected

**Steps to Reproduce**
1.  Login as an Admin user
2.  Create a project and add a `Language Engagement`
3.  Click on the `view details` button and Add `Product`  
4.  Select a `Scripture` and close the dropdown

**Expected Result**
 Validation message should not be displayed

**Actual Result**
`Product selection required` validation message is displayed when user collapsed 'Choose Product' field even scripture is selected

See video - 

https://user-images.githubusercontent.com/5212585/127449858-3880243f-2ed8-4f9b-b2b5-bd998efe7467.mp4

**FYI:** @ParkeBrown @michaelmarshall 

cord-field# 9ef5397

**Comment by CarsonF** [comment]
Must be a regression from my recent changes
