### ISSUE TITLE
Goals & Progress | Tracking for Other Goals

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#909]
Allow users to select the metric they use for tracking progress on Other Goals.
- percentage
- number
- done/not done

Other Goals will only have a single step (completed)

Other Goals will have a Description

**Comment by sethmcknight** [comment]
@CarsonF ready for you to add notes

**Comment by CarsonF** [comment]
I believe this will become a third type implementing `Product`, maybe `OtherProduct`.

@sethmcknight we need a way to label these. Maybe we should have a "short description" or "title" or "label" field as well? This would allow more details to be given in the description without looking bad in lists or having to truncate.

Providing a metric enum to choose the type of progress tracking isn't hard, but actually following through on that is going to be tricky.
One possible option is to treat all options as a number and just change the display. 
- percentage: X% out of 100%
- number: X out of Y
- boolean: 0/100
Y or total would need to be stored, which could be the number given or 100 for percent/boolean.

This would fit into our existing schema pretty relatively easily.
It does put us in a box though, if we need to add a type of progress that's not a number. Maybe a checklist or maybe two values are needed, or a relation to another object. I'm having a hard time coming up with an example so it's probably not going to happen.

**Comment by sethmcknight** [comment]
@CarsonF yeah, a title and description sound good to me.

**Comment by CarsonF** [comment]
Remaining work is covered in #925
