### ISSUE TITLE
Goals & Progress  | Rename Fields

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#910]
- [x]  Rename Products to Goals
- [ ]  Restrict ‘Scripture’ Goals to 1 book or portions of 1 book? A UI restriction only (at least for this)
- [x]  Change Product to Goal
- [ ]  Change Goal Type Song to EthnoArts
- [x] ~Change Goal Type Literacy Materials to Other~ (Covered in #909)
- [x] ~Add Approach & Methodology for Other Goals~ (Covered in #909)

**Comment by CarsonF** [comment]
@sethmcknight If Literacy Materials becomes "Other" but we are also adding "Other" with #909, then we have two others. Do you mean to just drop LitMat and convert it to the other mentioned in #909?

**Comment by sethmcknight** [comment]
@CarsonF yes, that works.

**Comment by CarsonF** [comment]
Let's just start with renaming in the UI only where possible
