### ISSUE TITLE
Project > Post > "Required" error message is blink while user add text in summary textbox and "submit" it

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#917]
**Roles**: All

**Describe the bug**
Project > Post > `Required` error message is blink while user add text in summary textbox and `submit` it

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and Open created project
3. Click on Add `Post` button and Select `Category` >  `story`
4. Select `Shareability` > `project team` and Add text in `Summary` textbox
5. Click on the `Submit` button

**Expected Result**
`Required` error message should not be blink while the user add text
 
**Actual Result**
`Required` error message is blinking while the user adds the text in summary textbox and `submit` it.

See video -   

https://user-images.githubusercontent.com/5212585/128692006-f98deeb3-5ba4-41e0-9f5b-17138fdad780.mp4

**Note** -  `Language engagement` also given `Required` validation message while clicking on the `Cancel` button

https://user-images.githubusercontent.com/5212585/128692040-d00e7f80-cb3e-46ac-9222-c66634c3caf6.mp4

**FYI**@ParkeBrown @michaelmarshall 

cord-field# 12e6b19
CordAPIV3# 08f111e

**Comment by CarsonF** [comment]
@iPiyushPatel FYI:

@daniel-leod fixed the use case when creating posts, which was the form values being reverted to an initial state while the API submission is happening.

The language engagement use case is different. It's a required field being "touched" by a user and then "blurred" as the cancel button is clicked. So the required field is in an invalid state before we ever get to the point of starting a close dialog animation. There's really know way to know that the user is trying to close the dialog and have that logic block the focused/blurred state/logic of the required field.
I hope that makes sense. So I'm calling that use case a _won't fix_. It's only shown for a very short amount of time too (about 195 milliseconds). Where as the other case, where we are waiting up to a couple seconds for the API to respond.
