### ISSUE TITLE
People > Create Person > "First Name" mandatory field is not highlighted while user leave blank the field and click on the "Submit" button

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#918]
**Roles**: All

**Describe the bug**
People > Create Person > `First Name` mandatory field is not highlighted while user leave blank the field and click on the `Submit` button

**Steps to Reproduce**
1. Login as Root admin
2. Create a new Person and Leave blank the mandatory field
3. Click on the `Submit` button

**Expected Result**
`First Name` mandatory field should be highlighted
 
**Actual Result**
`First Name` mandatory field is not highlighted while the user leaves blank the field and Click on the `Submit` button.

See screenshot -
![validation_not_displayed](https://user-images.githubusercontent.com/5212585/128842470-9bcdfe0a-16e9-4a34-8117-ce224532605d.png)
   
**FYI**@ParkeBrown @michaelmarshall 

cord-field# 12e6b19
CordAPIV3# 08f111e

**Comment by parashara1** [comment]
Successfully reproduced, not sure if bug label applies for something this small. However when creating a new person and leaving all mandatory fields blank, every field title is highlighted other than "First Name". Note: The "required" highlighted field is still present.

**Comment by CarsonF** [comment]
This is as expected. We focus the first invalid field on submit. So this field is displaying as focused hence the green label. The helper text below still showing the error & in red. And if the field is blurred it the label will change to red.
