### ISSUE TITLE
Project > Create product > "Completion Description" field data is not displayed in proper alignment

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#928]
Roles All

**Describe the bug**
Project > Create product > `Completion Description` field data is not displayed in proper alignment

**Steps to Reproduce**
1. Login as Admin user
2. Create a project and Open created project
3. Add `Start-End` date and Create `LanguageEngagment`
4. Click on the `View` button
5. Click on the `Add product` button  and Add product details
6. Enter Unlimited data in the `Completion Description` field
7. Click on the `Submit` button and click on the `Edit` product button

**Expected Result**
`Completion Description` field data should be displayed in Proper alignment
 
**Actual Result**
`Completion Description` field data is not displayed in proper alignment

See video -

https://user-images.githubusercontent.com/5212585/129570143-722fd91e-3f7b-42bc-9ba0-19e9a6eab066.mp4

![processed](https://user-images.githubusercontent.com/5212585/129571499-c0e6ca49-d4de-4b2b-807c-310ad252d7e5.jpeg)

**FYI**@ParkeBrown @michaelmarshall

cord-field# 1fc2795
CordAPIV3# 9190940

**Comment by parashara1** [comment]
`Completion Description` field data is not displayed properly even with custom alignment when entering the data.

**Comment by Rhuan288souza** [comment]
Adjusted `Complete Description` to break if the text if too long
![image](https://user-images.githubusercontent.com/19892952/129975459-8b394227-e1c3-4826-867e-d5c7b1f39bea.png)
