### ISSUE TITLE
Change Requests | Ceremony is not created when Engagement added via Change Request

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#933]
We need to re-add a Title and Toggle to the Dedication card on Engagements to explain what the card is and denote if a Dedication is Planned or Not Planned

These can be added to the actual card rather than placed above the card.

**Comment by sethmcknight** [comment]
Exists
<img width="469" alt="Screen Shot 2021-08-18 at 10 06 32 AM" src="https://user-images.githubusercontent.com/7377802/129933148-3eab4b65-451a-41dc-8d31-896e7a72bafa.png">

Missing
<img width="439" alt="Screen Shot 2021-08-18 at 10 06 40 AM" src="https://user-images.githubusercontent.com/7377802/129933151-67e0e694-c7ad-43b6-919f-e472d32e8c4f.png">

**Comment by CarsonF** [comment]
It looks like this is because the API returned null for the ceremony. So that's the root problem.
