### ISSUE TITLE
Preset Inventory

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-field#941]
Preset Inventory Flag

Field will be selecting Preset Inventory for Advancement to connect Investors to as part of our Language Offering.

Project Managers will make this selection at the Project level, but it will be applied to the Language Engagements. If a Language Engagement has an Investor connected we may need to automatically flag new Language Engagements with that Language as Approved Inventory.

This flag will need to be:

Selected, stored, and displayed on the Project Details page
Displayed on the Project Card
Displayed on the Language Engagement Card
Displayed on the Language Engagement Details
Displayed on the Language Card
Displayed on the Language Details
We'd also like to add Preset Inventory as a filter to the Projects list and Languages list

If a language has a project marked as Preset Inventory, that language should show (read-only) as Preset Inventory.

Here are the icons. @CarsonF removed all of Adobe Illustrator's junk (99% of the file size)

<svg viewBox="0 0 24 24">
  <g>
    <path d="M7.1 15h4.4v2H7.1zM7.1 11h7v2h-7zM7.1 7h7v2h-7z"/>
    <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 11v5H5V5h14v9z"/>
  </g>
</svg>
<svg viewBox="0 0 24 24">
  <g>
    <path d="M20 3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM10 17H5v-2h5v2zm0-4H5v-2h5v2zm0-4H5V7h5v2zm4.8 6L12 12.2l1.4-1.4 1.4 1.4L18 9l1.4 1.4-4.6 4.6z" />
  </g>
</svg>
They look like this:
Screen Shot 2021-09-02 at 10 07 26 AM

**Comment by sethmcknight** [comment]
@CarsonF & @zkhin thanks for your work on this! Everything here is looking great!

I just see one issue that needs to be resolved. Once a Project has been selected as Preset Inventory, all Language Engagements in the Project should be marked as Preset Inventory. We're currently showing this on the Project Card, Project Details, Language Card, and Language Details.

We need to add this icon to display on the Language Engagement Card and Language Engagement Details.

**Comment by CarsonF** [comment]
@zkhin Can you do this? I don't want to add anything to the API, just pull the prop from the project. 
Note it's only for language engagements not internship engagements.

**Comment by zkhin** [comment]
> @zkhin Can you do this? I don't want to add anything to the API, just pull the prop from the project.
> Note it's only for language engagements not internship engagements.

Sure, I will do that
