### ISSUE TITLE
G&P | Project > Goals > Blank suggestion dropdown is displayed while the user enters text in the "Completion Description" field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-field#956]
**Roles:** All

**Describe the bug**
Project > Goals > Blank suggestion dropdown is displayed while the user enters text in the `Completion Description` field

**Steps to Reproduce**

1.  Login as a root user
1.  Create a project and open a project detail page
1.  Add `LanguageEngagement` and click on the `View Details`
1.  Click on the `Add Goal` button and enter detail in the `Completion Description` field

**Expected Result**
Blank suggestion dropdown should not be displayed while the users enter text in the `Completion Description` field

**Actual Result**
Blank suggestion dropdown is displayed while the user enters text in the `Completion Description` field

See video - 

https://user-images.githubusercontent.com/5212585/136959042-53bdcd11-7620-439f-81dc-d39dbe7f0e7c.mp4

**FYI:** ParkeBrown michaelmarshall

cord-field# e7deacf

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466803013) by [Unito](https://www.unito.io)

**Comment by sethmcknight** [comment]
@CarsonF  would it work to put some placeholder text in the results that says "No Suggestions Found" or something like that?
