### ISSUE TITLE
G&P | For non-scripture Goals, allow scripture references across multiple books

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-field#997]
For Scripture Goals, we restrict scripture references to no more than a single full book.

For all other Goals (Story, Film, EthnoArt, Other) we need to allow scripture references across multiple books. For example story about a parable could pull from multiple gospels.

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466807396) by [Unito](https://www.unito.io)

**Comment by CarsonF** [comment]
I think it would be best to have the current scripture fields be unique for DirectScriptureProducts. The other two types could use something completely different.

Current thought in my mind:
- It needs to support multiple, so pull in [`react-final-form-arrays`](https://github.com/final-form/react-final-form-arrays)
- Each item would have a start & end input.
- I'm not sure if chapter/verse should be a separate input for each side or if it could just be merged with the book input.
- Chapter/verse should be optional which would default to start/end chapter/verse of the range
- End book could be auto set to the start book if it is blank.

**Comment by sherijennings** [comment]
<img width="1074" alt="story ex" src="https://user-images.githubusercontent.com/113928117/195155931-76e83e60-278f-4126-ae01-225d54237462.png">

When creating a goal for 1 story often users need to reference multiple books, chapters and verses. Currently you can only add 1 book but multiple chapters and verses
Example story: 'John the Baptist- Prepare the way' May reference Matthew 3:1-12, Mk 1:3-8 and Lk 3:2-17 
Currently the system does not allow user to input the additional books, chapters & verses
Request: Allow multiple books, chapters and verses to be manually input for a single story goal (cordfield). 
Add + to UI to input multiple books, chapters and verses utilizing existing UI 
At this time user is not requesting limit on number of b,ch,ver that can be input
